locations = [
    #Location name, region name, entrance name list
    #List missing a lot of data, should be enough to generate without logic
    "Kokiri Sword Chest",
    "Mido Top Left Chest",
    "Mido Top Right Chest",
    "Mido Bottom Left Chest",
    "Mido Bottom Right Chest",
    "Storms Grotto Chest",
    "Near Shortcuts Grotto Chest",
    "Skull Kid",
    "Trade Cojiro",
    "Trade Odd Potion",
    "Ocarina Memory Game",
    "Target in Woods",
    "Deku Scrub Near Deku Theater Right",
    "Deku Scrub Near Deku Theater Left",
    "Deku Scrub Near Bridge",
    "Deku Scrub Grotto Rear",
    "Deku Scrub Grotto Front",
    "Deku Theater Skull Mask",
    "Deku Theater Mask of Truth",
    "Wolfos Grotto Chest",
    "Deku Scrub Grotto Rear",
    "Deku Scrub Grotto Front",
    "Southeast Grotto Chest",
    "Open Grotto Chest",
    "Near Market Grotto Chest",
    "Ocarina of Time Item",
    "Tektite Grotto Freestanding PoH",
    "Deku Scrub Grotto",
    "Child Fishing",
    "Adult Fishing",
    "Hyrule Loach Reward",
    "Lab Dive",
    "Lab Trade Eyeball Frog",
    "Underwater Item",
    "Sun",
    "Freestanding PoH",
    "Deku Scrub Grotto Left",
    "Deku Scrub Grotto Right",
    "Deku Scrub Grotto Center",
    "Chest",
    "Trade Saw",
    "Waterfall Freestanding PoH",
    "Crate Freestanding PoH",
    "Deku Scrub Grotto Rear",
    "Deku Scrub Grotto Front",
    "Chest",
    "HBA 1000 Points",
    "HBA 1500 Points",
    "Gerudo Membership Card",
    "North F1 Carpenter",
    "North F2 Carpenter",
    "South F1 Carpenter",
    "South F2 Carpenter",
    "Chest",
    "Carpet Salesman",
    "Freestanding PoH",
    "Deku Scrub Grotto Rear",
    "Deku Scrub Grotto Front",
    "Treasure Chest Game Reward",
    "Bombchu Bowling First Prize",
    "Bombchu Bowling Second Prize",
    "Lost Dog",
    "Shooting Gallery",
    "10 Big Poes",
    "Chest Game First Room Item",
    "Chest Game Second Room Item",
    "Chest Game Third Room Item",
    "Chest Game Fourth Room Item",
    "Chest Game Fifth Room Item",
    "Chest Game First Room Key",
    "Chest Game Second Room Key",
    "Chest Game Third Room Key",
    "Chest Game Fourth Room Key",
    "Chest Game Fifth Room Key",
    "Malon Egg",
    "Zeldas Letter",
    "Redead Grotto Chest",
    "Open Grotto Chest",
    "10 Gold Skulltula Reward",
    "20 Gold Skulltula Reward",
    "30 Gold Skulltula Reward",
    "40 Gold Skulltula Reward",
    "50 Gold Skulltula Reward",
    "100 Gold Skulltula Reward",
    "Man on Roof",
    "Shooting Gallery Reward",
    "Trade Odd Mushroom",
    "Granny's Shop",
    "Anju as Adult",
    "Anju as Child",
    "Trade Pocket Cucco",
    "Impas House Freestanding PoH",
    "Windmill Freestanding PoH",
    "Shield Grave Chest",
    "Heart Piece Grave Chest",
    "Royal Family's Tomb Chest",
    "Hookshot Chest",
    "Freestanding PoH",
    "Dampe Race Freestanding PoH",
    "Dampe Gravedigging Tour",
    "Chest",
    "Storms Grotto Chest",
    "Trade Broken Sword",
    "Trade Eyedrops",
    "Trade Claim Check",
    "Freestanding PoH",
    "Maze Left Chest",
    "Maze Right Chest",
    "Maze Center Chest",
    "Rolling Goron as Child",
    "Rolling Goron as Adult",
    "Darunias Joy",
    "Pot Freestanding PoH",
    "Deku Scrub Grotto Left",
    "Deku Scrub Grotto Right",
    "Deku Scrub Grotto Center",
    "Medigoron",
    "Upper Grotto Chest",
    "Wall Freestanding PoH",
    "Volcano Freestanding PoH",
    "Deku Scrub",
    "Deku Scrub Grotto Left",
    "Deku Scrub Grotto Right",
    "Deku Scrub Grotto Center",
    "Open Grotto Chest",
    "Magic Bean Salesman",
    "Frogs Zelda's Lullaby",
    "Frogs Epona's Song",
    "Frogs Saria's Song",
    "Frogs Sun's Song",
    "Frogs Song of Time",
    "Frogs in the Rain",
    "Frogs Ocarina Game",
    "Near Open Grotto Freestanding PoH",
    "Near Domain Freestanding PoH",
    "Deku Scrub Grotto Rear",
    "Deku Scrub Grotto Front",
    "Chest",
    "Diving Minigame",
    "King Zora Thawed",
    "Trade Prescription",
    "Iceberg Freestanding PoH",
    "Bottom Freestanding PoH",
    "Talons Chickens",
    "Freestanding PoH",
    "Deku Scrub Grotto Left",
    "Deku Scrub Grotto Right",
    "Deku Scrub Grotto Center",
    "Map Chest",
    "Compass Chest",
    "Compass Room Side Chest",
    "Basement Chest",
    "Slingshot Chest",
    "Slingshot Room Side Chest",
    "MQ Map Chest",
    "MQ Compass Chest",
    "MQ Slingshot Chest",
    "MQ Slingshot Room Back Chest",
    "MQ Basement Chest",
    "MQ Before Spinning Log Chest",
    "MQ After Spinning Log Chest",
    "MQ Deku Scrub",
    "Boss Room Chest",
    "Map Chest",
    "Compass Chest",
    "Bomb Flower Platform Chest",
    "Bomb Bag Chest",
    "End Of Bridge Chest",
    "Deku Scrub Near Bomb Bag Left",
    "Deku Scrub Side Room Near Dodongos",
    "Deku Scrub Near Bomb Bag Right",
    "Deku Scrub Lobby",
    "MQ Map Chest",
    "MQ Bomb Bag Chest",
    "MQ Compass Chest",
    "MQ Larvae Room Chest",
    "MQ Torch Puzzle Room Chest",
    "MQ Under Grave Chest",
    "MQ Deku Scrub Lobby Rear",
    "MQ Deku Scrub Lobby Front",
    "MQ Deku Scrub Staircase",
    "MQ Deku Scrub Side Room Near Lower Lizalfos",
    "Map Chest",
    "Compass Chest",
    "Boomerang Chest",
    "Deku Scrub",
    "MQ First Room Side Chest",
    "MQ Map Chest",
    "MQ Second Room Lower Chest",
    "MQ Compass Chest",
    "MQ Second Room Upper Chest",
    "MQ Basement Near Switches Chest",
    "MQ Basement Near Vines Chest",
    "MQ Near Boss Chest",
    "MQ Falling Like Like Room Chest",
    "MQ Boomerang Room Small Chest",
    "MQ Boomerang Chest",
    "First Room Chest",
    "First Stalfos Chest",
    "Raised Island Courtyard Chest",
    "Map Chest",
    "Well Chest",
    "Falling Ceiling Room Chest",
    "Eye Switch Chest",
    "Boss Key Chest",
    "Floormaster Chest",
    "Bow Chest",
    "Red Poe Chest",
    "Blue Poe Chest",
    "Basement Chest",
    "MQ First Room Chest",
    "MQ Wolfos Chest",
    "MQ Bow Chest",
    "MQ Raised Island Courtyard Lower Chest",
    "MQ Raised Island Courtyard Upper Chest",
    "MQ Well Chest",
    "MQ Map Chest",
    "MQ Compass Chest",
    "MQ Falling Ceiling Room Chest",
    "MQ Basement Chest",
    "MQ Redead Chest",
    "MQ Boss Key Chest",
    "Near Boss Chest",
    "Flare Dancer Chest",
    "Boss Key Chest",
    "Big Lava Room Blocked Door Chest",
    "Big Lava Room Lower Open Door Chest",
    "Boulder Maze Lower Chest",
    "Boulder Maze Upper Chest",
    "Boulder Maze Side Room Chest",
    "Boulder Maze Shortcut Chest",
    "Scarecrow Chest",
    "Map Chest",
    "Compass Chest",
    "Highest Goron Chest",
    "Megaton Hammer Chest",
    "MQ Near Boss Chest",
    "MQ Megaton Hammer Chest",
    "MQ Compass Chest",
    "MQ Lizalfos Maze Lower Chest",
    "MQ Lizalfos Maze Upper Chest",
    "MQ Chest on Fire",
    "MQ Map Room Side Chest",
    "MQ Map Chest",
    "MQ Boss Key Chest",
    "MQ Big Lava Room Blocked Door Chest",
    "MQ Lizalfos Maze Side Room Chest",
    "MQ Freestanding Key",
    "Map Chest",
    "Compass Chest",
    "Torches Chest",
    "Dragon Chest",
    "Central Bow Target Chest",
    "Central Pillar Chest",
    "Cracked Wall Chest",
    "Boss Key Chest",
    "Longshot Chest",
    "River Chest",
    "MQ Central Pillar Chest",
    "MQ Boss Key Chest",
    "MQ Longshot Chest",
    "MQ Compass Chest",
    "MQ Map Chest",
    "MQ Freestanding Key",
    "Silver Gauntlets Chest",
    "Mirror Shield Chest",
    "Child Bridge Chest",
    "Child Early Torches Chest",
    "Compass Chest",
    "Early Adult Right Chest",
    "First Mirror Left Chest",
    "First Mirror Right Chest",
    "Map Chest",
    "Child Climb North Chest",
    "Child Climb East Chest",
    "Sun Block Room Chest",
    "Statue Room Hand Chest",
    "Statue Room Northeast Chest",
    "Near Four Armos Chest",
    "Hallway Right Invisible Chest",
    "Hallway Left Invisible Chest",
    "Boss Key Chest",
    "Topmost Chest",
    "MQ Entrance Front Left Chest",
    "MQ Entrance Back Right Chest",
    "MQ Entrance Front Right Chest",
    "MQ Entrance Back Left Chest",
    "MQ Child Hammer Switch Chest",
    "MQ Map Chest",
    "MQ Map Room Enemy Chest",
    "MQ Child Climb North Chest",
    "MQ Child Climb South Chest",
    "MQ Compass Chest",
    "MQ Statue Room Lullaby Chest",
    "MQ Statue Room Invisible Chest",
    "MQ Silver Block Hallway Chest",
    "MQ Sun Block Room Chest",
    "MQ Symphony Room Chest",
    "MQ Leever Room Chest",
    "MQ Beamos Room Chest",
    "MQ Chest Switch Chest",
    "MQ Boss Key Chest",
    "MQ Mirror Puzzle Invisible Chest",
    "Map Chest",
    "Hover Boots Chest",
    "Compass Chest",
    "Early Silver Rupee Chest",
    "Invisible Blades Visible Chest",
    "Invisible Blades Invisible Chest",
    "Falling Spikes Lower Chest",
    "Falling Spikes Upper Chest",
    "Falling Spikes Switch Chest",
    "Invisible Spikes Chest",
    "Wind Hint Chest",
    "After Wind Enemy Chest",
    "After Wind Hidden Chest",
    "Spike Walls Left Chest",
    "Boss Key Chest",
    "Invisible Floormaster Chest",
    "Freestanding Key",
    "MQ Compass Chest",
    "MQ Hover Boots Chest",
    "MQ Early Gibdos Chest",
    "MQ Map Chest",
    "MQ Beamos Silver Rupees Chest",
    "MQ Falling Spikes Switch Chest",
    "MQ Falling Spikes Lower Chest",
    "MQ Falling Spikes Upper Chest",
    "MQ Invisible Spikes Chest",
    "MQ Boss Key Chest",
    "MQ Spike Walls Left Chest",
    "MQ Stalfos Room Chest",
    "MQ Invisible Blades Invisible Chest",
    "MQ Invisible Blades Visible Chest",
    "MQ Bomb Flower Chest",
    "MQ Wind Hint Chest",
    "MQ After Wind Hidden Chest",
    "MQ After Wind Enemy Chest",
    "MQ Near Ship Invisible Chest",
    "MQ Freestanding Key",
    "Front Left Fake Wall Chest",
    "Front Center Bombable Chest",
    "Right Bottom Fake Wall Chest",
    "Compass Chest",
    "Center Skulltula Chest",
    "Back Left Bombable Chest",
    "Lens of Truth Chest",
    "Invisible Chest",
    "Underwater Front Chest",
    "Underwater Left Chest",
    "Map Chest",
    "Fire Keese Chest",
    "Like Like Chest",
    "Freestanding Key",
    "MQ Map Chest",
    "MQ Lens of Truth Chest",
    "MQ Compass Chest",
    "MQ Dead Hand Freestanding Key",
    "MQ East Inner Room Freestanding Key",
    "Map Chest",
    "Compass Chest",
    "Iron Boots Chest",
    "Freestanding PoH",
    "MQ Iron Boots Chest",
    "MQ Compass Chest",
    "MQ Map Chest",
    "MQ Freestanding PoH",
    "Lobby Left Chest",
    "Lobby Right Chest",
    "Stalfos Chest",
    "Beamos Chest",
    "Hidden Ceiling Chest",
    "Maze Path First Chest",
    "Maze Path Second Chest",
    "Maze Path Third Chest",
    "Maze Path Final Chest",
    "Maze Right Central Chest",
    "Maze Right Side Chest",
    "Underwater Silver Rupee Chest",
    "Hammer Room Clear Chest",
    "Hammer Room Switch Chest",
    "Eye Statue Chest",
    "Near Scarecrow Chest",
    "Before Heavy Block Chest",
    "Heavy Block First Chest",
    "Heavy Block Second Chest",
    "Heavy Block Third Chest",
    "Heavy Block Fourth Chest",
    "Freestanding Key",
    "MQ Lobby Right Chest",
    "MQ Lobby Left Chest",
    "MQ First Iron Knuckle Chest",
    "MQ Before Heavy Block Chest",
    "MQ Eye Statue Chest",
    "MQ Flame Circle Chest",
    "MQ Second Iron Knuckle Chest",
    "MQ Dinolfos Chest",
    "MQ Ice Arrows Chest",
    "MQ Maze Right Central Chest",
    "MQ Maze Path First Chest",
    "MQ Maze Right Side Chest",
    "MQ Maze Path Third Chest",
    "MQ Maze Path Second Chest",
    "MQ Hidden Ceiling Chest",
    "MQ Underwater Silver Rupee Chest",
    "MQ Heavy Block Chest",
    "Tower Boss Key Chest",
    "Forest Trial Chest",
    "Water Trial Left Chest",
    "Water Trial Right Chest",
    "Shadow Trial Front Chest",
    "Shadow Trial Golden Gauntlets Chest",
    "Spirit Trial Crystal Switch Chest",
    "Spirit Trial Invisible Chest",
    "Light Trial First Left Chest",
    "Light Trial Second Left Chest",
    "Light Trial Third Left Chest",
    "Light Trial First Right Chest",
    "Light Trial Second Right Chest",
    "Light Trial Third Right Chest",
    "Light Trial Invisible Enemies Chest",
    "Light Trial Lullaby Chest",
    "Deku Scrub Center-Left",
    "Deku Scrub Center-Right",
    "Deku Scrub Right",
    "Deku Scrub Left",
    "MQ Water Trial Chest",
    "MQ Forest Trial Eye Switch Chest",
    "MQ Forest Trial Frozen Eye Switch Chest",
    "MQ Light Trial Lullaby Chest",
    "MQ Shadow Trial Bomb Flower Chest",
    "MQ Shadow Trial Eye Switch Chest",
    "MQ Spirit Trial Golden Gauntlets Chest",
    "MQ Spirit Trial Sun Back Right Chest",
    "MQ Spirit Trial Sun Back Left Chest",
    "MQ Spirit Trial Sun Front Left Chest",
    "MQ Spirit Trial First Chest",
    "MQ Spirit Trial Invisible Chest",
    "MQ Forest Trial Freestanding Key",
    "MQ Deku Scrub Right",
    "MQ Deku Scrub Center-Left",
    "MQ Deku Scrub Center",
    "MQ Deku Scrub Center-Right",
    "MQ Deku Scrub Left",
    "GS Basement Back Room",
    "GS Basement Gate",
    "GS Basement Vines",
    "GS Compass Room",
    "MQ GS Lobby",
    "MQ GS Past Boulder Vines",
    "MQ GS Basement Graves Room",
    "MQ GS Basement Back Room",
    "GS Vines Above Stairs",
    "GS Scarecrow",
    "GS Alcove Above Stairs",
    "GS Back Room",
    "GS Side Room Near Lower Lizalfos",
    "MQ GS Scrub Room",
    "MQ GS Song of Time Block Room",
    "MQ GS Lizalfos Room",
    "MQ GS Larvae Room",
    "MQ GS Back Room",
    "GS Lobby Basement Lower",
    "GS Lobby Basement Upper",
    "GS Near Boss",
    "GS Water Switch Room",
    "MQ GS Tail Parasan Room",
    "MQ GS Invisible Enemies Room",
    "MQ GS Boomerang Chest Room",
    "MQ GS Near Boss",
    "GS Raised Island Courtyard",
    "GS First Room",
    "GS Level Island Courtyard",
    "GS Lobby",
    "GS Basement",
    "MQ GS First Hallway",
    "MQ GS Block Push Room",
    "MQ GS Raised Island Courtyard",
    "MQ GS Level Island Courtyard",
    "MQ GS Well",
    "GS Song of Time Room",
    "GS Boss Key Loop",
    "GS Boulder Maze",
    "GS Scarecrow Top",
    "GS Scarecrow Climb",
    "MQ GS Above Fire Wall Maze",
    "MQ GS Fire Wall Maze Center",
    "MQ GS Big Lava Room Open Door",
    "MQ GS Fire Wall Maze Side Room",
    "MQ GS Skull on Fire",
    "GS Behind Gate",
    "GS Falling Platform Room",
    "GS Central Pillar",
    "GS Near Boss Key Chest",
    "GS River",
    "MQ GS Before Upper Water Switch",
    "MQ GS Freestanding Key Area",
    "MQ GS Lizalfos Hallway",
    "MQ GS River",
    "MQ GS Triple Wall Torch",
    "GS Hall After Sun Block Room",
    "GS Boulder Room",
    "GS Lobby",
    "GS Sun on Floor Room",
    "GS Metal Fence",
    "MQ GS Symphony Room",
    "MQ GS Leever Room",
    "MQ GS Nine Thrones Room West",
    "MQ GS Nine Thrones Room North",
    "MQ GS Sun Block Room",
    "GS Single Giant Pot",
    "GS Falling Spikes Room",
    "GS Triple Giant Pot",
    "GS Like Like Room",
    "GS Near Ship",
    "MQ GS Falling Spikes Room",
    "MQ GS Wind Hint Room",
    "MQ GS After Wind",
    "MQ GS After Ship",
    "MQ GS Near Boss",
    "GS Like Like Cage",
    "GS East Inner Room",
    "GS West Inner Room",
    "MQ GS Basement",
    "MQ GS Coffin Room",
    "MQ GS West Inner Room",
    "GS Push Block Room",
    "GS Spinning Scythe Room",
    "GS Heart Piece Room",
    "MQ GS Scarecrow",
    "MQ GS Ice Block",
    "MQ GS Red Ice",
    "GS Bean Patch",
    "GS Know It All House",
    "GS House of Twins",
    "GS Bean Patch Near Bridge",
    "GS Bean Patch Near Theater",
    "GS Above Theater",
    "GS",
    "GS Cow Grotto",
    "GS Stone Bridge Tree Grotto",
    "GS Bean Patch",
    "GS Small Island",
    "GS Lab Wall",
    "GS Lab Crate",
    "GS Tree",
    "GS Bean Patch",
    "GS Small Bridge",
    "GS Pillar",
    "GS Behind Tent",
    "GS Archery Range",
    "GS Top Floor",
    "GS",
    "GS Bean Patch",
    "GS Hill",
    "GS Tree",
    "OGC GS",
    "GS Storms Grotto",
    "GS Tree",
    "Market GS Guard House",
    "GS House Under Construction",
    "GS Skulltula House",
    "GS Guards House",
    "GS Tree",
    "GS Watchtower",
    "GS Above Impas House",
    "GS Wall",
    "GS Bean Patch",
    "GS Bean Patch",
    "GS Crate",
    "GS Bean Patch",
    "GS Near Kak",
    "GS Above Dodongos Cavern",
    "GS Falling Rocks Path",
    "GS Center Platform",
    "GS Boulder Maze",
    "GS Ladder",
    "GS Tree",
    "GS Above Bridge",
    "GS Near Raised Grottos",
    "GS Frozen Waterfall",
    "GS Above The Log",
    "GS Hidden Cave",
    "GS Tree",
    "GS Back Wall",
    "GS Rain Shed",
    "GS House Window",
    "GS Tree",
    "Link's Pocket",
    "Queen Gohma",
    "King Dodongo",
    "Barinade",
    "Phantom Ganon",
    "Volvagia",
    "Morpha",
    "Twinrova",
    "Bongo Bongo",
    "Ganon",
    "Gift from Rauru",
    "Queen Gohma Heart Container",
    "King Dodongo Heart Container",
    "Barinade Heart Container",
    "Phantom Ganon Heart Container",
    "Volvagia Heart Container",
    "Morpha Heart Container",
    "Twinrova Heart Container",
    "Bongo Bongo Heart Container",
    "ToT Master Sword",
    "ToT Light Arrow Cutscene",
    "Gift From Saria",
    "Great Fairy Reward",
    "Great Fairy Reward",
    "Great Fairy Reward",
    "Great Fairy Reward",
    "Great Fairy Reward",
    "OGC Great Fairy Reward",
    "Sheik in Forest",
    "Sheik in Crater",
    "Sheik in Ice Cavern",
    "Sheik at Colossus",
    "Sheik in Kakariko",
    "Sheik at Temple",
    "Song from Impa",
    "Song from Malon",
    "Song from Saria",
    "Song from Royal Family's Tomb",
    "Song from Ocarina of Time",
    "Song from Windmill",
    "Storms Grotto Beehive Left",
    "Storms Grotto Beehive Right",
    "Tunnel Grotto Beehive Left",
    "Tunnel Grotto Beehive Right",
    "Deku Scrub Grotto Beehive",
    "Deku Scrub Grotto Beehive",
    "Near Market Grotto Beehive Left",
    "Near Market Grotto Beehive Right",
    "Open Grotto Beehive Left",
    "Open Grotto Beehive Right",
    "Southeast Grotto Beehive Left",
    "Southeast Grotto Beehive Right",
    "Deku Scrub Grotto Beehive",
    "Deku Scrub Grotto Beehive",
    "Open Grotto Beehive Left",
    "Open Grotto Beehive Right",
    "Cow Grotto Beehive",
    "Storms Grotto Beehive Left",
    "Storms Grotto Beehive Right",
    "Grotto Beehive",
    "Upper Grotto Beehive Left",
    "Upper Grotto Beehive Right",
    "Hammer Grotto Beehive",
    "Open Grotto Beehive Left",
    "Open Grotto Beehive Right",
    "Storms Grotto Beehive",
    "In Front of King Zora Beehive Left",
    "In Front of King Zora Beehive Right",
    "Behind King Zora Beehive",
    "Deku Scrub Grotto Beehive",
    "Deku Scrub Grotto Beehive",
    "Deku Scrub Grotto Beehive",
    "Shop Item 1",
    "Shop Item 2",
    "Shop Item 3",
    "Shop Item 4",
    "Shop Item 5",
    "Shop Item 6",
    "Shop Item 7",
    "Shop Item 8",
    "Potion Shop Item 1",
    "Potion Shop Item 2",
    "Potion Shop Item 3",
    "Potion Shop Item 4",
    "Potion Shop Item 5",
    "Potion Shop Item 6",
    "Potion Shop Item 7",
    "Potion Shop Item 8",
    "Bazaar Item 1",
    "Bazaar Item 2",
    "Bazaar Item 3",
    "Bazaar Item 4",
    "Bazaar Item 5",
    "Bazaar Item 6",
    "Bazaar Item 7",
    "Bazaar Item 8",
    "Bombchu Shop Item 1",
    "Bombchu Shop Item 2",
    "Bombchu Shop Item 3",
    "Bombchu Shop Item 4",
    "Bombchu Shop Item 5",
    "Bombchu Shop Item 6",
    "Bombchu Shop Item 7",
    "Bombchu Shop Item 8",
    "Potion Shop Item 1",
    "Potion Shop Item 2",
    "Potion Shop Item 3",
    "Potion Shop Item 4",
    "Potion Shop Item 5",
    "Potion Shop Item 6",
    "Potion Shop Item 7",
    "Potion Shop Item 8",
    "Bazaar Item 1",
    "Bazaar Item 2",
    "Bazaar Item 3",
    "Bazaar Item 4",
    "Bazaar Item 5",
    "Bazaar Item 6",
    "Bazaar Item 7",
    "Bazaar Item 8",
    "Shop Item 1",
    "Shop Item 2",
    "Shop Item 3",
    "Shop Item 4",
    "Shop Item 5",
    "Shop Item 6",
    "Shop Item 7",
    "Shop Item 8",
    "Shop Item 1",
    "Shop Item 2",
    "Shop Item 3",
    "Shop Item 4",
    "Shop Item 5",
    "Shop Item 6",
    "Shop Item 7",
    "Shop Item 8",
    "Gossip Stone",
    "Gossip Stone",
    "Gossip Stone",
    "Gossip Stone",
    "Gossip Stone",
    "Maze Gossip Stone",
    "Medigoron Gossip Stone",
    "Gossip Stone",
    "Malon Gossip Stone",
    "Rock Wall Gossip Stone",
    "Storms Grotto Gossip Stone",
    "Deku Tree Left Gossip Stone",
    "Deku Tree Right Gossip Stone",
    "Gossip Stone",
    "Storms Gossip Stone",
    "Lab Gossip Stone",
    "Southeast Gossip Stone",
    "Southwest Gossip Stone",
    "Gossip Stone",
    "Maze Lower Gossip Stone",
    "Maze Upper Gossip Stone",
    "Saria Gossip Stone",
    "ToT Left Gossip Stone",
    "ToT Right Gossip Stone",
    "ToT Right Center Gossip Stone",
    "ToT Left Center Gossip Stone",
    "Gossip Stone",
    "Fairy Gossip Stone",
    "Jabu Gossip Stone",
    "Near Grottos Gossip Stone",
    "Near Domain Gossip Stone",
    "Cow Grotto Gossip Stone",
    "Near Market Gossip Stone",
    "Southeast Gossip Stone",
    "Open Grotto Gossip Stone",
    "Open Grotto Gossip Stone",
    "Open Grotto Gossip Stone",
    "Near Shortcuts Grotto Gossip Stone",
    "Storms Grotto Gossip Stone",
    "Upper Grotto Gossip Stone",
    "Ganondorf Hint",
    "Sheik Hint",
    "Sheik Hint",
    "Diary Hint",
    "Greg Hint",
    "Sarias Song Hint",
    "ToT Child Altar Hint",
    "ToT Adult Altar Hint",
    "Fishing Pole Hint",
    "Ocarina of Time Hint",
    "Mask Shop Hint",
    "Completed Triforce"
]

loc_id_by_name = {name: id for id, name in enumerate(locations)}

entrances = [
    #Entrance name, Location 1 name, Location 2 name, Access rule
]