locations = [
"Link's Pocket",
"Queen Gohma",
"King Dodongo",
"Barinade",
"Phantom Ganon",
"Volvagia",
"Morpha",
"Bongo Bongo",
"Twinrova",
"Ganon",
"Gift from Rauru",
"Song from Impa",
"Song from Malon",
"Song from Saria",
"Song from Royal Family's Tomb",
"Song from Ocarina of Time",
"Song from Windmill",
"Sheik in Forest",
"Sheik in Crater",
"Sheik in Ice Cavern",
"Sheik at Colossus",
"Sheik in Kakariko",
"Sheik at Temple",
"KF Mido Top Left Chest",
"KF Mido Top Right Chest",
"KF Mido Bottom Left Chest",
"KF Mido Bottom Right Chest",
"KF Kokiri Sword Chest",
"KF Storms Grotto Chest",
"KF Links House Cow",
"KF GS Know It All House",
"KF GS Bean Patch",
"KF GS House of Twins",
"KF Shop Item 1",
"KF Shop Item 2",
"KF Shop Item 3",
"KF Shop Item 4",
"KF Shop Item 5",
"KF Shop Item 6",
"KF Shop Item 7",
"KF Shop Item 8",
"LW Gift From Saria",
"LW Ocarina Memory Game",
"LW Target in Woods",
"LW Near Shortcuts Grotto Chest",
"LW Trade Cojiro",
"LW Deku Theater Skull Mask",
"LW Deku Theater Mask of Truth",
"LW Skull Kid",
"LW Trade Odd Potion",
"LW Deku Scrub Near Bridge",
"LW Deku Scrub Near Deku Theater Left",
"LW Deku Scrub Near Deku Theater Right",
"LW Deku Scrub Grotto Front",
"LW Deku Scrub Grotto Rear",
"LW GS Bean Patch Near Bridge",
"LW GS Bean Patch Near Theater",
"LW GS Above Theater",
"SFM Wolfos Grotto Chest",
"SFM Deku Scrub Grotto Front",
"SFM Deku Scrub Grotto Rear",
"SFM GS",
"HF Ocarina of Time Item",
"HF Near Market Grotto Chest",
"HF Tektite Grotto Freestanding PoH",
"HF Southeast Grotto Chest",
"HF Open Grotto Chest",
"HF Deku Scrub Grotto",
"HF Cow Grotto Cow",
"HF GS Cow Grotto",
"HF GS Stone Bridge Tree Grotto",
"Market Shooting Gallery",
"Market Bombchu Bowling First Prize",
"Market Bombchu Bowling Second Prize",
"Market Lost Dog",
"Market Treasure Chest Game Reward",
"Market 10 Big Poes",
"Market Chest Game First Room Item",
"Market Chest Game Second Room Item",
"Market Chest Game Third Room Item",
"Market Chest Game Fourth Room Item",
"Market Chest Game Fifth Room Item",
"Market Chest Game First Room Key",
"Market Chest Game Second Room Key",
"Market Chest Game Third Room Key",
"Market Chest Game Fourth Room Key",
"Market Chest Game Fifth Room Key",
"Market Market GS Guard House",
"Market Bazaar Item 1",
"Market Bazaar Item 2",
"Market Bazaar Item 3",
"Market Bazaar Item 4",
"Market Bazaar Item 5",
"Market Bazaar Item 6",
"Market Bazaar Item 7",
"Market Bazaar Item 8",
"Market Potion Shop Item 1",
"Market Potion Shop Item 2",
"Market Potion Shop Item 3",
"Market Potion Shop Item 4",
"Market Potion Shop Item 5",
"Market Potion Shop Item 6",
"Market Potion Shop Item 7",
"Market Potion Shop Item 8",
"Market Bombchu Shop Item 1",
"Market Bombchu Shop Item 2",
"Market Bombchu Shop Item 3",
"Market Bombchu Shop Item 4",
"Market Bombchu Shop Item 5",
"Market Bombchu Shop Item 6",
"Market Bombchu Shop Item 7",
"Market Bombchu Shop Item 8",
"Market ToT Light Arrow Cutscene",
"Market ToT Master Sword",
"HC Malon Egg",
"HC Zeldas Letter",
"HC Great Fairy Reward",
"HC GS Tree",
"HC GS Storms Grotto",
"LLR Talons Chickens",
"LLR Freestanding PoH",
"LLR Deku Scrub Grotto Left",
"LLR Deku Scrub Grotto Center",
"LLR Deku Scrub Grotto Right",
"LLR Stables Left Cow",
"LLR Stables Right Cow",
"LLR Tower Left Cow",
"LLR Tower Right Cow",
"LLR GS House Window",
"LLR GS Tree",
"LLR GS Rain Shed",
"LLR GS Back Wall",
"Kak Anju as Child",
"Kak Anju as Adult",
"Kak Impas House Freestanding PoH",
"Kak Windmill Freestanding PoH",
"Kak Man on Roof",
"Kak Open Grotto Chest",
"Kak Redead Grotto Chest",
"Kak Shooting Gallery Reward",
"Kak Trade Odd Mushroom",
"Kak Granny's Shop",
"Kak Trade Pocket Cucco",
"Kak 10 Gold Skulltula Reward",
"Kak 20 Gold Skulltula Reward",
"Kak 30 Gold Skulltula Reward",
"Kak 40 Gold Skulltula Reward",
"Kak 50 Gold Skulltula Reward",
"Kak 100 Gold Skulltula Reward",
"Kak Impas House Cow",
"Kak GS Tree",
"Kak GS Guards House",
"Kak GS Watchtower",
"Kak GS Skulltula House",
"Kak GS House Under Construction",
"Kak GS Above Impas House",
"Kak Bazaar Item 1",
"Kak Bazaar Item 2",
"Kak Bazaar Item 3",
"Kak Bazaar Item 4",
"Kak Bazaar Item 5",
"Kak Bazaar Item 6",
"Kak Bazaar Item 7",
"Kak Bazaar Item 8",
"Kak Potion Shop Item 1",
"Kak Potion Shop Item 2",
"Kak Potion Shop Item 3",
"Kak Potion Shop Item 4",
"Kak Potion Shop Item 5",
"Kak Potion Shop Item 6",
"Kak Potion Shop Item 7",
"Kak Potion Shop Item 8",
"Graveyard Shield Grave Chest",
"Graveyard Heart Piece Grave Chest",
"Graveyard Royal Family's Tomb Chest",
"Graveyard Freestanding PoH",
"Graveyard Dampe Gravedigging Tour",
"Graveyard Hookshot Chest",
"Graveyard Dampe Race Freestanding PoH",
"Graveyard GS Bean Patch",
"Graveyard GS Wall",
"DMT Freestanding PoH",
"DMT Chest",
"DMT Storms Grotto Chest",
"DMT Trade Broken Sword",
"DMT Trade Eyedrops",
"DMT Trade Claim Check",
"DMT Great Fairy Reward",
"DMT Cow Grotto Cow",
"DMT GS Near Kak",
"DMT GS Bean Patch",
"DMT GS Above Dodongos Cavern",
"DMT GS Falling Rocks Path",
"GC Darunias Joy",
"GC Pot Freestanding PoH",
"GC Rolling Goron as Child",
"GC Rolling Goron as Adult",
"GC Medigoron",
"GC Maze Left Chest",
"GC Maze Right Chest",
"GC Maze Center Chest",
"GC Deku Scrub Grotto Left",
"GC Deku Scrub Grotto Center",
"GC Deku Scrub Grotto Right",
"GC GS Center Platform",
"GC GS Boulder Maze",
"GC Shop Item 1",
"GC Shop Item 2",
"GC Shop Item 3",
"GC Shop Item 4",
"GC Shop Item 5",
"GC Shop Item 6",
"GC Shop Item 7",
"GC Shop Item 8",
"DMC Volcano Freestanding PoH",
"DMC Wall Freestanding PoH",
"DMC Upper Grotto Chest",
"DMC Great Fairy Reward",
"DMC Deku Scrub",
"DMC Deku Scrub Grotto Left",
"DMC Deku Scrub Grotto Center",
"DMC Deku Scrub Grotto Right",
"DMC GS Crate",
"DMC GS Bean Patch",
"ZR Magic Bean Salesman",
"ZR Open Grotto Chest",
"ZR Frogs Zelda's Lullaby",
"ZR Frogs Epona's Song",
"ZR Frogs Saria's Song",
"ZR Frogs Sun's Song",
"ZR Frogs Song of Time",
"ZR Frogs in the Rain",
"ZR Frogs Ocarina Game",
"ZR Near Open Grotto Freestanding PoH",
"ZR Near Domain Freestanding PoH",
"ZR Deku Scrub Grotto Front",
"ZR Deku Scrub Grotto Rear",
"ZR GS Tree",
"ZR GS Ladder",
"ZR GS Near Raised Grottos",
"ZR GS Above Bridge",
"ZD Diving Minigame",
"ZD Chest",
"ZD King Zora Thawed",
"ZD Trade Prescription",
"ZD GS Frozen Waterfall",
"ZD Shop Item 1",
"ZD Shop Item 2",
"ZD Shop Item 3",
"ZD Shop Item 4",
"ZD Shop Item 5",
"ZD Shop Item 6",
"ZD Shop Item 7",
"ZD Shop Item 8",
"ZF Great Fairy Reward",
"ZF Iceberg Freestanding PoH",
"ZF Bottom Freestanding PoH",
"ZF GS Above The Log",
"ZF GS Tree",
"ZF GS Hidden Cave",
"LH Underwater Item",
"LH Child Fishing",
"LH Child Pond Fish 1",
"LH Child Pond Fish 2",
"LH Child Pond Fish 3",
"LH Child Pond Fish 4",
"LH Child Pond Fish 5",
"LH Child Pond Fish 6",
"LH Child Pond Fish 7",
"LH Child Pond Fish 8",
"LH Child Pond Fish 9",
"LH Child Pond Fish 10",
"LH Child Pond Fish 11",
"LH Child Pond Fish 12",
"LH Child Pond Fish 13",
"LH Child Pond Fish 14",
"LH Child Pond Fish 15",
"LH Child Pond Loach 1",
"LH Child Pond Loach 2",
"LH Adult Fishing",
"LH Hyrule Loach Reward",
"LH Adult Pond Fish 1",
"LH Adult Pond Fish 2",
"LH Adult Pond Fish 3",
"LH Adult Pond Fish 4",
"LH Adult Pond Fish 5",
"LH Adult Pond Fish 6",
"LH Adult Pond Fish 7",
"LH Adult Pond Fish 8",
"LH Adult Pond Fish 9",
"LH Adult Pond Fish 10",
"LH Adult Pond Fish 11",
"LH Adult Pond Fish 12",
"LH Adult Pond Fish 13",
"LH Adult Pond Fish 14",
"LH Adult Pond Fish 15",
"LH Adult Pond Loach",
"LH Lab Dive",
"LH Lab Trade Eyeball Frog",
"LH Freestanding PoH",
"LH Sun",
"LH Deku Scrub Grotto Left",
"LH Deku Scrub Grotto Center",
"LH Deku Scrub Grotto Right",
"LH GS Bean Patch",
"LH GS Lab Wall",
"LH GS Small Island",
"LH GS Lab Crate",
"LH GS Tree",
"GV Crate Freestanding PoH",
"GV Waterfall Freestanding PoH",
"GV Chest",
"GV Trade Saw",
"GV Deku Scrub Grotto Front",
"GV Deku Scrub Grotto Rear",
"GV Cow",
"GV GS Small Bridge",
"GV GS Bean Patch",
"GV GS Behind Tent",
"GV GS Pillar",
"GF Chest",
"GF HBA 1000 Points",
"GF HBA 1500 Points",
"GF Gerudo Membership Card",
"GF North F1 Carpenter",
"GF North F2 Carpenter",
"GF South F1 Carpenter",
"GF South F2 Carpenter",
"GF GS Top Floor",
"GF GS Archery Range",
"",
"",
"",
"",
"",
"Wasteland Carpet Salesman",
"Wasteland Chest",
"Wasteland GS",
"Colossus Great Fairy Reward",
"Colossus Freestanding PoH",
"Colossus Deku Scrub Grotto Front",
"Colossus Deku Scrub Grotto Rear",
"Colossus GS Bean Patch",
"Colossus GS Tree",
"Colossus GS Hill",
"OGC Great Fairy Reward",
"HC OGC GS",
"Deku Tree Map Chest",
"Deku Tree Slingshot Room Side Chest",
"Deku Tree Slingshot Chest",
"Deku Tree Compass Chest",
"Deku Tree Compass Room Side Chest",
"Deku Tree Basement Chest",
"Deku Tree GS Compass Room",
"Deku Tree GS Basement Vines",
"Deku Tree GS Basement Gate",
"Deku Tree GS Basement Back Room",
"Deku Tree MQ Map Chest",
"Deku Tree MQ Slingshot Chest",
"Deku Tree MQ Slingshot Room Back Chest",
"Deku Tree MQ Compass Chest",
"Deku Tree MQ Basement Chest",
"Deku Tree MQ Before Spinning Log Chest",
"Deku Tree MQ After Spinning Log Chest",
"Deku Tree MQ Deku Scrub",
"Deku Tree MQ GS Lobby",
"Deku Tree MQ GS Past Boulder Vines",
"Deku Tree MQ GS Basement Graves Room",
"Deku Tree MQ GS Basement Back Room",
"Deku Tree Queen Gohma Heart Container",
"Dodongos Cavern Map Chest",
"Dodongos Cavern Compass Chest",
"Dodongos Cavern Bomb Flower Platform Chest",
"Dodongos Cavern Bomb Bag Chest",
"Dodongos Cavern End Of Bridge Chest",
"Dodongos Cavern Deku Scrub Side Room Near Dodongos",
"Dodongos Cavern Deku Scrub Lobby",
"Dodongos Cavern Deku Scrub Near Bomb Bag Left",
"Dodongos Cavern Deku Scrub Near Bomb Bag Right",
"Dodongos Cavern GS Side Room Near Lower Lizalfos",
"Dodongos Cavern GS Scarecrow",
"Dodongos Cavern GS Alcove Above Stairs",
"Dodongos Cavern GS Vines Above Stairs",
"Dodongos Cavern GS Back Room",
"Dodongos Cavern MQ Map Chest",
"Dodongos Cavern MQ Bomb Bag Chest",
"Dodongos Cavern MQ Torch Puzzle Room Chest",
"Dodongos Cavern MQ Larvae Room Chest",
"Dodongos Cavern MQ Compass Chest",
"Dodongos Cavern MQ Under Grave Chest",
"Dodongos Cavern MQ Deku Scrub Lobby Front",
"Dodongos Cavern MQ Deku Scrub Lobby Rear",
"Dodongos Cavern MQ Deku Scrub Side Room Near Lower Lizalfos",
"Dodongos Cavern MQ Deku Scrub Staircase",
"Dodongos Cavern MQ GS Scrub Room",
"Dodongos Cavern MQ GS Larvae Room",
"Dodongos Cavern MQ GS Lizalfos Room",
"Dodongos Cavern MQ GS Song of Time Block Room",
"Dodongos Cavern MQ GS Back Room",
"Dodongos Cavern Boss Room Chest",
"Dodongos Cavern King Dodongo Heart Container",
"Jabu Jabus Belly Boomerang Chest",
"Jabu Jabus Belly Map Chest",
"Jabu Jabus Belly Compass Chest",
"Jabu Jabus Belly Deku Scrub",
"Jabu Jabus Belly GS Water Switch Room",
"Jabu Jabus Belly GS Lobby Basement Lower",
"Jabu Jabus Belly GS Lobby Basement Upper",
"Jabu Jabus Belly GS Near Boss",
"Jabu Jabus Belly MQ Map Chest",
"Jabu Jabus Belly MQ First Room Side Chest",
"Jabu Jabus Belly MQ Second Room Lower Chest",
"Jabu Jabus Belly MQ Compass Chest",
"Jabu Jabus Belly MQ Basement Near Switches Chest",
"Jabu Jabus Belly MQ Basement Near Vines Chest",
"Jabu Jabus Belly MQ Boomerang Room Small Chest",
"Jabu Jabus Belly MQ Boomerang Chest",
"Jabu Jabus Belly MQ Falling Like Like Room Chest",
"Jabu Jabus Belly MQ Second Room Upper Chest",
"Jabu Jabus Belly MQ Near Boss Chest",
"Jabu Jabus Belly MQ Cow",
"Jabu Jabus Belly MQ GS Boomerang Chest Room",
"Jabu Jabus Belly MQ GS Tail Parasan Room",
"Jabu Jabus Belly MQ GS Invisible Enemies Room",
"Jabu Jabus Belly MQ GS Near Boss",
"Jabu Jabus Belly Barinade Heart Container",
"Bottom of the Well Front Left Fake Wall Chest",
"Bottom of the Well Front Center Bombable Chest",
"Bottom of the Well Back Left Bombable Chest",
"Bottom of the Well Underwater Left Chest",
"Bottom of the Well Freestanding Key",
"Bottom of the Well Compass Chest",
"Bottom of the Well Center Skulltula Chest",
"Bottom of the Well Right Bottom Fake Wall Chest",
"Bottom of the Well Fire Keese Chest",
"Bottom of the Well Like Like Chest",
"Bottom of the Well Map Chest",
"Bottom of the Well Underwater Front Chest",
"Bottom of the Well Invisible Chest",
"Bottom of the Well Lens of Truth Chest",
"Bottom of the Well GS West Inner Room",
"Bottom of the Well GS East Inner Room",
"Bottom of the Well GS Like Like Cage",
"Bottom of the Well MQ Map Chest",
"Bottom of the Well MQ East Inner Room Freestanding Key",
"Bottom of the Well MQ Compass Chest",
"Bottom of the Well MQ Dead Hand Freestanding Key",
"Bottom of the Well MQ Lens of Truth Chest",
"Bottom of the Well MQ GS Coffin Room",
"Bottom of the Well MQ GS West Inner Room",
"Bottom of the Well MQ GS Basement",
"Forest Temple First Room Chest",
"Forest Temple First Stalfos Chest",
"Forest Temple Raised Island Courtyard Chest",
"Forest Temple Map Chest",
"Forest Temple Well Chest",
"Forest Temple Eye Switch Chest",
"Forest Temple Boss Key Chest",
"Forest Temple Floormaster Chest",
"Forest Temple Red Poe Chest",
"Forest Temple Bow Chest",
"Forest Temple Blue Poe Chest",
"Forest Temple Falling Ceiling Room Chest",
"Forest Temple Basement Chest",
"Forest Temple GS First Room",
"Forest Temple GS Lobby",
"Forest Temple GS Raised Island Courtyard",
"Forest Temple GS Level Island Courtyard",
"Forest Temple GS Basement",
"Forest Temple MQ First Room Chest",
"Forest Temple MQ Wolfos Chest",
"Forest Temple MQ Well Chest",
"Forest Temple MQ Raised Island Courtyard Lower Chest",
"Forest Temple MQ Raised Island Courtyard Upper Chest",
"Forest Temple MQ Boss Key Chest",
"Forest Temple MQ Redead Chest",
"Forest Temple MQ Map Chest",
"Forest Temple MQ Bow Chest",
"Forest Temple MQ Compass Chest",
"Forest Temple MQ Falling Ceiling Room Chest",
"Forest Temple MQ Basement Chest",
"Forest Temple MQ GS First Hallway",
"Forest Temple MQ GS Raised Island Courtyard",
"Forest Temple MQ GS Level Island Courtyard",
"Forest Temple MQ GS Well",
"Forest Temple MQ GS Block Push Room",
"Forest Temple Phantom Ganon Heart Container",
"Fire Temple Near Boss Chest",
"Fire Temple Flare Dancer Chest",
"Fire Temple Boss Key Chest",
"Fire Temple Big Lava Room Lower Open Door Chest",
"Fire Temple Big Lava Room Blocked Door Chest",
"Fire Temple Boulder Maze Lower Chest",
"Fire Temple Boulder Maze Side Room Chest",
"Fire Temple Map Chest",
"Fire Temple Boulder Maze Shortcut Chest",
"Fire Temple Boulder Maze Upper Chest",
"Fire Temple Scarecrow Chest",
"Fire Temple Compass Chest",
"Fire Temple Megaton Hammer Chest",
"Fire Temple Highest Goron Chest",
"Fire Temple GS Boss Key Loop",
"Fire Temple GS Song of Time Room",
"Fire Temple GS Boulder Maze",
"Fire Temple GS Scarecrow Climb",
"Fire Temple GS Scarecrow Top",
"Fire Temple MQ Map Room Side Chest",
"Fire Temple MQ Megaton Hammer Chest",
"Fire Temple MQ Map Chest",
"Fire Temple MQ Near Boss Chest",
"Fire Temple MQ Big Lava Room Blocked Door Chest",
"Fire Temple MQ Boss Key Chest",
"Fire Temple MQ Lizalfos Maze Side Room Chest",
"Fire Temple MQ Compass Chest",
"Fire Temple MQ Lizalfos Maze Upper Chest",
"Fire Temple MQ Lizalfos Maze Lower Chest",
"Fire Temple MQ Freestanding Key",
"Fire Temple MQ Chest on Fire",
"Fire Temple MQ GS Big Lava Room Open Door",
"Fire Temple MQ GS Skull on Fire",
"Fire Temple MQ GS Fire Wall Maze Center",
"Fire Temple MQ GS Fire Wall Maze Side Room",
"Fire Temple MQ GS Above Fire Wall Maze",
"Fire Temple Volvagia Heart Container",
"Water Temple Compass Chest",
"Water Temple Map Chest",
"Water Temple Cracked Wall Chest",
"Water Temple Torches Chest",
"Water Temple Boss Key Chest",
"Water Temple Central Pillar Chest",
"Water Temple Central Bow Target Chest",
"Water Temple Longshot Chest",
"Water Temple River Chest",
"Water Temple Dragon Chest",
"Water Temple GS Behind Gate",
"Water Temple GS Near Boss Key Chest",
"Water Temple GS Central Pillar",
"Water Temple GS Falling Platform Room",
"Water Temple GS River",
"Water Temple MQ Longshot Chest",
"Water Temple MQ Map Chest",
"Water Temple MQ Compass Chest",
"Water Temple MQ Central Pillar Chest",
"Water Temple MQ Boss Key Chest",
"Water Temple MQ Freestanding Key",
"Water Temple MQ GS Lizalfos Hallway",
"Water Temple MQ GS Before Upper Water Switch",
"Water Temple MQ GS River",
"Water Temple MQ GS Freestanding Key Area",
"Water Temple MQ GS Triple Wall Torch",
"Water Temple Morpha Heart Container",
"Shadow Temple Map Chest",
"Shadow Temple Hover Boots Chest",
"Shadow Temple Compass Chest",
"Shadow Temple Early Silver Rupee Chest",
"Shadow Temple Invisible Blades Visible Chest",
"Shadow Temple Invisible Blades Invisible Chest",
"Shadow Temple Falling Spikes Lower Chest",
"Shadow Temple Falling Spikes Upper Chest",
"Shadow Temple Falling Spikes Switch Chest",
"Shadow Temple Invisible Spikes Chest",
"Shadow Temple Freestanding Key",
"Shadow Temple Wind Hint Chest",
"Shadow Temple After Wind Enemy Chest",
"Shadow Temple After Wind Hidden Chest",
"Shadow Temple Spike Walls Left Chest",
"Shadow Temple Boss Key Chest",
"Shadow Temple Invisible Floormaster Chest",
"Shadow Temple GS Like Like Room",
"Shadow Temple GS Falling Spikes Room",
"Shadow Temple GS Single Giant Pot",
"Shadow Temple GS Near Ship",
"Shadow Temple GS Triple Giant Pot",
"Shadow Temple MQ Early Gibdos Chest",
"Shadow Temple MQ Map Chest",
"Shadow Temple MQ Near Ship Invisible Chest",
"Shadow Temple MQ Compass Chest",
"Shadow Temple MQ Hover Boots Chest",
"Shadow Temple MQ Invisible Blades Invisible Chest",
"Shadow Temple MQ Invisible Blades Visible Chest",
"Shadow Temple MQ Beamos Silver Rupees Chest",
"Shadow Temple MQ Falling Spikes Lower Chest",
"Shadow Temple MQ Falling Spikes Upper Chest",
"Shadow Temple MQ Falling Spikes Switch Chest",
"Shadow Temple MQ Invisible Spikes Chest",
"Shadow Temple MQ Stalfos Room Chest",
"Shadow Temple MQ Wind Hint Chest",
"Shadow Temple MQ After Wind Hidden Chest",
"Shadow Temple MQ After Wind Enemy Chest",
"Shadow Temple MQ Boss Key Chest",
"Shadow Temple MQ Spike Walls Left Chest",
"Shadow Temple MQ Freestanding Key",
"Shadow Temple MQ Bomb Flower Chest",
"Shadow Temple MQ GS Falling Spikes Room",
"Shadow Temple MQ GS Wind Hint Room",
"Shadow Temple MQ GS After Wind",
"Shadow Temple MQ GS After Ship",
"Shadow Temple MQ GS Near Boss",
"Shadow Temple Bongo Bongo Heart Container",
"Spirit Temple Child Bridge Chest",
"Spirit Temple Child Early Torches Chest",
"Spirit Temple Child Climb North Chest",
"Spirit Temple Child Climb East Chest",
"Spirit Temple Map Chest",
"Spirit Temple Sun Block Room Chest",
"Spirit Temple MQ Entrance Front Left Chest",
"Spirit Temple MQ Entrance Back Right Chest",
"Spirit Temple MQ Entrance Front Right Chest",
"Spirit Temple MQ Entrance Back Left Chest",
"Spirit Temple MQ Map Chest",
"Spirit Temple MQ Map Room Enemy Chest",
"Spirit Temple MQ Child Climb North Chest",
"Spirit Temple MQ Child Climb South Chest",
"Spirit Temple MQ Compass Chest",
"Spirit Temple MQ Silver Block Hallway Chest",
"Spirit Temple MQ Sun Block Room Chest",
"Spirit Temple Silver Gauntlets Chest",
"Spirit Temple Compass Chest",
"Spirit Temple Early Adult Right Chest",
"Spirit Temple First Mirror Left Chest",
"Spirit Temple First Mirror Right Chest",
"Spirit Temple Statue Room Northeast Chest",
"Spirit Temple Statue Room Hand Chest",
"Spirit Temple Near Four Armos Chest",
"Spirit Temple Hallway Right Invisible Chest",
"Spirit Temple Hallway Left Invisible Chest",
"Spirit Temple MQ Child Hammer Switch Chest",
"Spirit Temple MQ Statue Room Lullaby Chest",
"Spirit Temple MQ Statue Room Invisible Chest",
"Spirit Temple MQ Leever Room Chest",
"Spirit Temple MQ Symphony Room Chest",
"Spirit Temple MQ Beamos Room Chest",
"Spirit Temple MQ Chest Switch Chest",
"Spirit Temple MQ Boss Key Chest",
"Spirit Temple Mirror Shield Chest",
"Spirit Temple Boss Key Chest",
"Spirit Temple Topmost Chest",
"Spirit Temple MQ Mirror Puzzle Invisible Chest",
"Spirit Temple GS Metal Fence",
"Spirit Temple GS Sun on Floor Room",
"Spirit Temple GS Hall After Sun Block Room",
"Spirit Temple GS Lobby",
"Spirit Temple GS Boulder Room",
"Spirit Temple MQ GS Sun Block Room",
"Spirit Temple MQ GS Leever Room",
"Spirit Temple MQ GS Symphony Room",
"Spirit Temple MQ GS Nine Thrones Room West",
"Spirit Temple MQ GS Nine Thrones Room North",
"Spirit Temple Twinrova Heart Container",
"Ice Cavern Map Chest",
"Ice Cavern Compass Chest",
"Ice Cavern Freestanding PoH",
"Ice Cavern Iron Boots Chest",
"Ice Cavern GS Spinning Scythe Room",
"Ice Cavern GS Heart Piece Room",
"Ice Cavern GS Push Block Room",
"Ice Cavern MQ Map Chest",
"Ice Cavern MQ Compass Chest",
"Ice Cavern MQ Freestanding PoH",
"Ice Cavern MQ Iron Boots Chest",
"Ice Cavern MQ GS Red Ice",
"Ice Cavern MQ GS Ice Block",
"Ice Cavern MQ GS Scarecrow",
"Gerudo Training Ground Lobby Left Chest",
"Gerudo Training Ground Lobby Right Chest",
"Gerudo Training Ground Stalfos Chest",
"Gerudo Training Ground Before Heavy Block Chest",
"Gerudo Training Ground Heavy Block First Chest",
"Gerudo Training Ground Heavy Block Second Chest",
"Gerudo Training Ground Heavy Block Third Chest",
"Gerudo Training Ground Heavy Block Fourth Chest",
"Gerudo Training Ground Eye Statue Chest",
"Gerudo Training Ground Near Scarecrow Chest",
"Gerudo Training Ground Hammer Room Clear Chest",
"Gerudo Training Ground Hammer Room Switch Chest",
"Gerudo Training Ground Freestanding Key",
"Gerudo Training Ground Maze Right Central Chest",
"Gerudo Training Ground Maze Right Side Chest",
"Gerudo Training Ground Underwater Silver Rupee Chest",
"Gerudo Training Ground Beamos Chest",
"Gerudo Training Ground Hidden Ceiling Chest",
"Gerudo Training Ground Maze Path First Chest",
"Gerudo Training Ground Maze Path Second Chest",
"Gerudo Training Ground Maze Path Third Chest",
"Gerudo Training Ground Maze Path Final Chest",
"Gerudo Training Ground MQ Lobby Left Chest",
"Gerudo Training Ground MQ Lobby Right Chest",
"Gerudo Training Ground MQ First Iron Knuckle Chest",
"Gerudo Training Ground MQ Before Heavy Block Chest",
"Gerudo Training Ground MQ Heavy Block Chest",
"Gerudo Training Ground MQ Eye Statue Chest",
"Gerudo Training Ground MQ Ice Arrows Chest",
"Gerudo Training Ground MQ Second Iron Knuckle Chest",
"Gerudo Training Ground MQ Flame Circle Chest",
"Gerudo Training Ground MQ Maze Right Central Chest",
"Gerudo Training Ground MQ Maze Right Side Chest",
"Gerudo Training Ground MQ Underwater Silver Rupee Chest",
"Gerudo Training Ground MQ Dinolfos Chest",
"Gerudo Training Ground MQ Hidden Ceiling Chest",
"Gerudo Training Ground MQ Maze Path First Chest",
"Gerudo Training Ground MQ Maze Path Third Chest",
"Gerudo Training Ground MQ Maze Path Second Chest",
"Ganon's Castle Forest Trial Chest",
"Ganon's Castle Water Trial Left Chest",
"Ganon's Castle Water Trial Right Chest",
"Ganon's Castle Shadow Trial Front Chest",
"Ganon's Castle Shadow Trial Golden Gauntlets Chest",
"Ganon's Castle Light Trial First Left Chest",
"Ganon's Castle Light Trial Second Left Chest",
"Ganon's Castle Light Trial Third Left Chest",
"Ganon's Castle Light Trial First Right Chest",
"Ganon's Castle Light Trial Second Right Chest",
"Ganon's Castle Light Trial Third Right Chest",
"Ganon's Castle Light Trial Invisible Enemies Chest",
"Ganon's Castle Light Trial Lullaby Chest",
"Ganon's Castle Spirit Trial Crystal Switch Chest",
"Ganon's Castle Spirit Trial Invisible Chest",
"Ganon's Castle Deku Scrub Left",
"Ganon's Castle Deku Scrub Center-Left",
"Ganon's Castle Deku Scrub Center-Right",
"Ganon's Castle Deku Scrub Right",
"Ganon's Castle MQ Forest Trial Freestanding Key",
"Ganon's Castle MQ Forest Trial Eye Switch Chest",
"Ganon's Castle MQ Forest Trial Frozen Eye Switch Chest",
"Ganon's Castle MQ Water Trial Chest",
"Ganon's Castle MQ Shadow Trial Bomb Flower Chest",
"Ganon's Castle MQ Shadow Trial Eye Switch Chest",
"Ganon's Castle MQ Light Trial Lullaby Chest",
"Ganon's Castle MQ Spirit Trial First Chest",
"Ganon's Castle MQ Spirit Trial Invisible Chest",
"Ganon's Castle MQ Spirit Trial Sun Front Left Chest",
"Ganon's Castle MQ Spirit Trial Sun Back Left Chest",
"Ganon's Castle MQ Spirit Trial Sun Back Right Chest",
"Ganon's Castle MQ Spirit Trial Golden Gauntlets Chest",
"Ganon's Castle MQ Deku Scrub Left",
"Ganon's Castle MQ Deku Scrub Center-Left",
"Ganon's Castle MQ Deku Scrub Center",
"Ganon's Castle MQ Deku Scrub Center-Right",
"Ganon's Castle MQ Deku Scrub Right",
"Ganon's Castle Tower Boss Key Chest",
"KF Links House Pot",
"KF Twins House Pot 1",
"KF Twins House Pot 2",
"KF Brothers House Pot 1",
"KF Brothers House Pot 2",
"GF Break Room Pot 1",
"GF Break Room Pot 2",
"GF Kitchen Pot 1",
"GF Kitchen Pot 2",
"GF North F1 Carpenter Pot 1",
"GF North F1 Carpenter Pot 2",
"GF North F1 Carpenter Pot 3",
"GF North F2 Carpenter Pot 1",
"GF North F2 Carpenter Pot 2",
"GF South F1 Carpenter Pot 1",
"GF South F1 Carpenter Pot 2",
"GF South F1 Carpenter Pot 3",
"GF South F1 Carpenter Cell Pot 1",
"GF South F1 Carpenter Cell Pot 2",
"GF South F1 Carpenter Cell Pot 3",
"GF South F1 Carpenter Cell Pot 4",
"Wasteland Near GS Pot 1",
"Wasteland Near GS Pot 2",
"Wasteland Near GS Pot 3",
"Wasteland Near GS Pot 4",
"HF Cow Grotto Pot 1",
"HF Cow Grotto Pot 2",
"Market Guard House Child Pot 1",
"Market Guard House Child Pot 2",
"Market Guard House Child Pot 3",
"Market Guard House Child Pot 4",
"Market Guard House Child Pot 5",
"Market Guard House Child Pot 6",
"Market Guard House Child Pot 7",
"Market Guard House Child Pot 8",
"Market Guard House Child Pot 9",
"Market Guard House Child Pot 10",
"Market Guard House Child Pot 11",
"Market Guard House Child Pot 12",
"Market Guard House Child Pot 13",
"Market Guard House Child Pot 14",
"Market Guard House Child Pot 15",
"Market Guard House Child Pot 16",
"Market Guard House Child Pot 17",
"Market Guard House Child Pot 18",
"Market Guard House Child Pot 19",
"Market Guard House Child Pot 20",
"Market Guard House Child Pot 21",
"Market Guard House Child Pot 22",
"Market Guard House Child Pot 23",
"Market Guard House Child Pot 24",
"Market Guard House Child Pot 25",
"Market Guard House Child Pot 26",
"Market Guard House Child Pot 27",
"Market Guard House Child Pot 28",
"Market Guard House Child Pot 29",
"Market Guard House Child Pot 30",
"Market Guard House Child Pot 31",
"Market Guard House Child Pot 32",
"Market Guard House Child Pot 33",
"Market Guard House Child Pot 34",
"Market Guard House Child Pot 35",
"Market Guard House Child Pot 36",
"Market Guard House Child Pot 37",
"Market Guard House Child Pot 38",
"Market Guard House Child Pot 39",
"Market Guard House Child Pot 40",
"Market Guard House Child Pot 41",
"Market Guard House Child Pot 42",
"Market Guard House Child Pot 43",
"Market Guard House Child Pot 44",
"Market Guard House Adult Pot 1",
"Market Guard House Adult Pot 2",
"Market Guard House Adult Pot 3",
"Market Guard House Adult Pot 4",
"Market Guard House Adult Pot 5",
"Market Guard House Adult Pot 6",
"Market Guard House Adult Pot 7",
"Market Guard House Adult Pot 8",
"Market Guard House Adult Pot 9",
"Market Guard House Adult Pot 10",
"Market Guard House Adult Pot 11",
"Market Back Alley House Pot 1",
"Market Back Alley House Pot 2",
"Market Back Alley House Pot 3",
"HC Storms Grotto Pot 1",
"HC Storms Grotto Pot 2",
"HC Storms Grotto Pot 3",
"HC Storms Grotto Pot 4",
"LLR Front Pot 1",
"LLR Front Pot 2",
"LLR Front Pot 3",
"LLR Front Pot 4",
"LLR Rain Shed Pot 1",
"LLR Rain Shed Pot 2",
"LLR Rain Shed Pot 3",
"LLR Talons House Pot 1",
"LLR Talons House Pot 2",
"LLR Talons House Pot 3",
"Kak Near Potion Shop Pot 1",
"Kak Near Potion Shop Pot 2",
"Kak Near Potion Shop Pot 3",
"Kak Near Impas House Pot 1",
"Kak Near Impas House Pot 2",
"Kak Near Impas House Pot 3",
"Kak Near Guards House Pot 1",
"Kak Near Guards House Pot 2",
"Kak Near Guards House Pot 3",
"Kak Near Medicine Shop Pot 1",
"Kak Near Medicine Shop Pot 2",
"Graveyard Dampes Grave Pot 1",
"Graveyard Dampes Grave Pot 2",
"Graveyard Dampes Grave Pot 3",
"Graveyard Dampes Grave Pot 4",
"Graveyard Dampes Grave Pot 5",
"Graveyard Dampes Grave Pot 6",
"GC Lower Staircase Pot 1",
"GC Lower Staircase Pot 2",
"GC Upper Staircase Pot 1",
"GC Upper Staircase Pot 2",
"GC Upper Staircase Pot 3",
"GC Medigoron Pot 1",
"GC Darunia Pot 1",
"GC Darunia Pot 2",
"GC Darunia Pot 3",
"DMC Near GC Pot 1",
"DMC Near GC Pot 2",
"DMC Near GC Pot 3",
"DMC Near GC Pot 4",
"ZD Near Shop Pot 1",
"ZD Near Shop Pot 2",
"ZD Near Shop Pot 3",
"ZD Near Shop Pot 4",
"ZD Near Shop Pot 5",
"ZF Hidden Cave Pot 1",
"ZF Hidden Cave Pot 2",
"ZF Hidden Cave Pot 3",
"ZF Near Jabu Pot 1",
"ZF Near Jabu Pot 2",
"ZF Near Jabu Pot 3",
"ZF Near Jabu Pot 4",
"Dodongos Cavern Lizalfos Pot 1",
"Dodongos Cavern Lizalfos Pot 2",
"Dodongos Cavern Lizalfos Pot 3",
"Dodongos Cavern Lizalfos Pot 4",
"Dodongos Cavern Side Room Pot 1",
"Dodongos Cavern Side Room Pot 2",
"Dodongos Cavern Side Room Pot 3",
"Dodongos Cavern Side Room Pot 4",
"Dodongos Cavern Side Room Pot 5",
"Dodongos Cavern Side Room Pot 6",
"Dodongos Cavern Torch Room Pot 1",
"Dodongos Cavern Torch Room Pot 2",
"Dodongos Cavern Torch Room Pot 3",
"Dodongos Cavern Torch Room Pot 4",
"Dodongos Cavern Staircase Pot 1",
"Dodongos Cavern Staircase Pot 2",
"Dodongos Cavern Staircase Pot 3",
"Dodongos Cavern Staircase Pot 4",
"Dodongos Cavern Single Eye Pot 1",
"Dodongos Cavern Single Eye Pot 2",
"Dodongos Cavern Blade Pot 1",
"Dodongos Cavern Blade Pot 2",
"Dodongos Cavern Double Eye Pot 1",
"Dodongos Cavern Double Eye Pot 2",
"Dodongos Cavern Back Room Pot 1",
"Dodongos Cavern Back Room Pot 2",
"Dodongos Cavern Back Room Pot 3",
"Dodongos Cavern Back Room Pot 4",
"Jabu Jabus Belly Above Big Octo Pot 1",
"Jabu Jabus Belly Above Big Octo Pot 2",
"Jabu Jabus Belly Above Big Octo Pot 3",
"Jabu Jabus Belly Barinade Pot 1",
"Jabu Jabus Belly Barinade Pot 2",
"Jabu Jabus Belly Barinade Pot 3",
"Jabu Jabus Belly Barinade Pot 4",
"Jabu Jabus Belly Barinade Pot 5",
"Jabu Jabus Belly Barinade Pot 6",
"Jabu Jabus Belly Basement Pot 1",
"Jabu Jabus Belly Basement Pot 2",
"Jabu Jabus Belly Basement Pot 3",
"Jabu Jabus Belly Two Octorok Pot 1",
"Jabu Jabus Belly Two Octorok Pot 2",
"Jabu Jabus Belly Two Octorok Pot 3",
"Jabu Jabus Belly Two Octorok Pot 4",
"Jabu Jabus Belly Two Octorok Pot 5",
"Bottom of the Well Basement Pot 1",
"Bottom of the Well Basement Pot 2",
"Bottom of the Well Basement Pot 3",
"Bottom of the Well Basement Pot 4",
"Bottom of the Well Basement Pot 5",
"Bottom of the Well Basement Pot 6",
"Bottom of the Well Basement Pot 7",
"Bottom of the Well Basement Pot 8",
"Bottom of the Well Basement Pot 9",
"Bottom of the Well Basement Pot 10",
"Bottom of the Well Basement Pot 11",
"Bottom of the Well Basement Pot 12",
"Bottom of the Well Left Side Pot 1",
"Bottom of the Well Left Side Pot 2",
"Bottom of the Well Left Side Pot 3",
"Bottom of the Well Near Entrance Pot 1",
"Bottom of the Well Near Entrance Pot 2",
"Bottom of the Well Fire Keese Pot 1",
"Bottom of the Well Underwater Pot",
"Forest Temple Lobby Pot 1",
"Forest Temple Lobby Pot 2",
"Forest Temple Lobby Pot 3",
"Forest Temple Lobby Pot 4",
"Forest Temple Lobby Pot 5",
"Forest Temple Lobby Pot 6",
"Forest Temple Lower Stalfos Pot 1",
"Forest Temple Lower Stalfos Pot 2",
"Forest Temple Green Poe Pot 1",
"Forest Temple Green Poe Pot 2",
"Forest Temple Upper Stalfos Pot 1",
"Forest Temple Upper Stalfos Pot 2",
"Forest Temple Upper Stalfos Pot 3",
"Forest Temple Upper Stalfos Pot 4",
"Forest Temple Blue Poe Pot 1",
"Forest Temple Blue Poe Pot 2",
"Forest Temple Blue Poe Pot 3",
"Forest Temple Frozen Eye Pot 1",
"Forest Temple Frozen Eye Pot 2",
"Fire Temple Near Boss Pot 1",
"Fire Temple Near Boss Pot 2",
"Fire Temple Near Boss Pot 3",
"Fire Temple Near Boss Pot 4",
"Fire Temple Big Lava Pot 1",
"Fire Temple Big Lava Pot 2",
"Fire Temple Big Lava Pot 3",
"Fire Temple Flame Maze Left Pot 1",
"Fire Temple Flame Maze Left Pot 2",
"Fire Temple Flame Maze Left Pot 3",
"Fire Temple Flame Maze Left Pot 4",
"Fire Temple Flame Maze Right Pot 1",
"Fire Temple Flame Maze Right Pot 2",
"Fire Temple Flame Maze Right Pot 3",
"Fire Temple Flame Maze Right Pot 4",
"Water Temple Main Level 2 Pot 1",
"Water Temple Main Level 2 Pot 2",
"Water Temple Main Level 1 Pot 1",
"Water Temple Main Level 1 Pot 2",
"Water Temple Torch Pot 1",
"Water Temple Torch Pot 2",
"Water Temple Near Compass Pot 1",
"Water Temple Near Compass Pot 2",
"Water Temple Near Compass Pot 3",
"Water Temple Central Bow Pot 1",
"Water Temple Central Bow Pot 2",
"Water Temple Behind Gate Pot 1",
"Water Temple Behind Gate Pot 2",
"Water Temple Behind Gate Pot 3",
"Water Temple Behind Gate Pot 4",
"Water Temple Basement Block Puzzle Pot 1",
"Water Temple Basement Block Puzzle Pot 2",
"Water Temple River Pot 1",
"Water Temple River Pot 2",
"Water Temple Like Like Pot 1",
"Water Temple Like Like Pot 2",
"Water Temple Boss Key Pot 1",
"Water Temple Boss Key Pot 2",
"Shadow Temple Near Dead Hand Pot 1",
"Shadow Temple Whispering Walls Pot 1",
"Shadow Temple Whispering Walls Pot 2",
"Shadow Temple Whispering Walls Pot 3",
"Shadow Temple Whispering Walls Pot 4",
"Shadow Temple Whispering Walls Pot 5",
"Shadow Temple Map Chest Pot 1",
"Shadow Temple Map Chest Pot 2",
"Shadow Temple Falling Spikes Pot 1",
"Shadow Temple Falling Spikes Pot 2",
"Shadow Temple Falling Spikes Pot 3",
"Shadow Temple Falling Spikes Pot 4",
"Shadow Temple After Wind Pot 1",
"Shadow Temple After Wind Pot 2",
"Shadow Temple Spike Walls Pot 1",
"Shadow Temple Floormaster Pot 1",
"Shadow Temple Floormaster Pot 2",
"Shadow Temple After Boat Pot 1",
"Shadow Temple After Boat Pot 2",
"Shadow Temple After Boat Pot 3",
"Shadow Temple After Boat Pot 4",
"Spirit Temple Lobby Pot 1",
"Spirit Temple Lobby Pot 2",
"Spirit Temple Anubis Pot 1",
"Spirit Temple Anubis Pot 2",
"Spirit Temple Anubis Pot 3",
"Spirit Temple Anubis Pot 4",
"Spirit Temple Child Climb Pot 1",
"Spirit Temple After Sun Block Pot 1",
"Spirit Temple After Sun Block Pot 2",
"Spirit Temple Central Chamber Pot 1",
"Spirit Temple Central Chamber Pot 2",
"Spirit Temple Central Chamber Pot 3",
"Spirit Temple Central Chamber Pot 4",
"Spirit Temple Central Chamber Pot 5",
"Spirit Temple Central Chamber Pot 6",
"Spirit Temple Beamos Hall Pot 1",
"Ice Cavern Hall Pot 1",
"Ice Cavern Hall Pot 2",
"Ice Cavern Spinning Blade Pot 1",
"Ice Cavern Spinning Blade Pot 2",
"Ice Cavern Spinning Blade Pot 3",
"Ice Cavern Near End Pot 1",
"Ice Cavern Near End Pot 2",
"Ice Cavern Frozen Pot 1",
"Ganon's Castle Forest Trial Pot 1",
"Ganon's Castle Forest Trial Pot 2",
"Ganon's Castle Fire Trial Pot 1",
"Ganon's Castle Fire Trial Pot 2",
"Ganon's Castle Water Trial Pot 1",
"Ganon's Castle Water Trial Pot 2",
"Ganon's Castle Water Trial Pot 3",
"Ganon's Castle Shadow Trial Pot 1",
"Ganon's Castle Shadow Trial Pot 2",
"Ganon's Castle Shadow Trial Pot 3",
"Ganon's Castle Shadow Trial Pot 4",
"Ganon's Castle Spirit Trial Pot 1",
"Ganon's Castle Spirit Trial Pot 2",
"Ganon's Castle Light Trial Boulder Pot 1",
"Ganon's Castle Light Trial Pot 1",
"Ganon's Castle Light Trial Pot 2",
"Ganon's Castle Ganons Tower Pot 1",
"Ganon's Castle Ganons Tower Pot 2",
"Ganon's Castle Ganons Tower Pot 3",
"Ganon's Castle Ganons Tower Pot 4",
"Ganon's Castle Ganons Tower Pot 5",
"Ganon's Castle Ganons Tower Pot 6",
"Ganon's Castle Ganons Tower Pot 7",
"Ganon's Castle Ganons Tower Pot 8",
"Ganon's Castle Ganons Tower Pot 9",
"Ganon's Castle Ganons Tower Pot 10",
"Ganon's Castle Ganons Tower Pot 11",
"Ganon's Castle Ganons Tower Pot 12",
"Ganon's Castle Ganons Tower Pot 13",
"Ganon's Castle Ganons Tower Pot 14",
"Ganon's Castle Ganons Tower Pot 15",
"Ganon's Castle Ganons Tower Pot 16",
"Ganon's Castle Ganons Tower Pot 17",
"Ganon's Castle Ganons Tower Pot 18",
"Dodongos Cavern MQ Staircase Pot 1",
"Dodongos Cavern MQ Staircase Pot 2",
"Dodongos Cavern MQ Staircase Pot 3",
"Dodongos Cavern MQ Staircase Pot 4",
"Dodongos Cavern MQ Torch Puzzle Middle Pot",
"Dodongos Cavern MQ Big Block Pot 1",
"Dodongos Cavern MQ Big Block Pot 2",
"Dodongos Cavern MQ Upper Lizalfos Pot 1",
"Dodongos Cavern MQ Upper Lizalfos Pot 2",
"Dodongos Cavern MQ Upper Lizalfos Pot 3",
"Dodongos Cavern MQ Upper Lizalfos Pot 4",
"Dodongos Cavern MQ Two Flames Pot 1",
"Dodongos Cavern MQ Two Flames Pot 2",
"Dodongos Cavern MQ Torch Puzzle Corner Pot",
"Dodongos Cavern MQ Right Side Pot 1",
"Dodongos Cavern MQ Right Side Pot 2",
"Dodongos Cavern MQ Right Side Pot 3",
"Dodongos Cavern MQ Right Side Pot 4",
"Dodongos Cavern MQ Poe Room Pot 1",
"Dodongos Cavern MQ Poe Room Pot 2",
"Dodongos Cavern MQ Poe Room Pot 3",
"Dodongos Cavern MQ Poe Room Pot 4",
"Dodongos Cavern MQ Before Boss SW Pot",
"Dodongos Cavern MQ Before Boss NE Pot",
"Dodongos Cavern MQ Armos Room SE Pot",
"Dodongos Cavern MQ Armos Room SW Pot",
"Dodongos Cavern MQ Backroom Pot 1",
"Dodongos Cavern MQ Backroom Pot 2",
"Dodongos Cavern MQ Armos Room NW Pot",
"Dodongos Cavern MQ Armos Room NE Pot",
"Jabu Jabus Belly MQ Entrance Pot 1",
"Jabu Jabus Belly MQ Entrance Pot 2",
"Jabu Jabus Belly MQ Geyser Pot 1",
"Jabu Jabus Belly MQ Geyser Pot 2",
"Jabu Jabus Belly MQ Time Block Pot 1",
"Jabu Jabus Belly MQ Time Block Pot 2",
"Jabu Jabus Belly MQ Like Likes Pot 1",
"Jabu Jabus Belly MQ Like Likes Pot 2",
"Jabu Jabus Belly MQ Before Boss Pot 1",
"Bottom of the Well MQ Inner Lobby Pot 1",
"Bottom of the Well MQ Inner Lobby Pot 2",
"Bottom of the Well MQ Inner Lobby Pot 3",
"Bottom of the Well MQ Outer Lobby Pot",
"Bottom of the Well MQ East Inner Pot 1",
"Bottom of the Well MQ East Inner Pot 2",
"Bottom of the Well MQ East Inner Pot 3",
"Forest Temple MQ Lobby Pot 1",
"Forest Temple MQ Lobby Pot 2",
"Forest Temple MQ Lobby Pot 3",
"Forest Temple MQ Lobby Pot 4",
"Forest Temple MQ Lobby Pot 5",
"Forest Temple MQ Lobby Pot 6",
"Forest Temple MQ Wolfos Pot 1",
"Forest Temple MQ Wolfos Pot 2",
"Forest Temple MQ Upper Stalfos Pot 1",
"Forest Temple MQ Upper Stalfos Pot 2",
"Forest Temple MQ Upper Stalfos Pot 3",
"Forest Temple MQ Upper Stalfos Pot 4",
"Forest Temple MQ Blue Poe Pot 1",
"Forest Temple MQ Blue Poe Pot 2",
"Forest Temple MQ Blue Poe Pot 3",
"Forest Temple MQ Green Poe Pot 1",
"Forest Temple MQ Green Poe Pot 2",
"Forest Temple MQ Basement Pot 1",
"Forest Temple MQ Basement Pot 2",
"Forest Temple MQ Basement Pot 3",
"Forest Temple MQ Basement Pot 4",
"Fire Temple MQ Entrance Pot 1",
"Fire Temple MQ Entrance Pot 2",
"Fire Temple MQ Before Mini Boss Pot 1",
"Fire Temple MQ Before Mini Boss Pot 2",
"Fire Temple MQ Before Mini Boss Pot 3",
"Fire Temple MQ Before Mini Boss Pot 4",
"Fire Temple MQ Before Mini Boss Pot 5",
"Fire Temple MQ Before Mini Boss Pot 6",
"Fire Temple MQ Before Mini Boss Pot 7",
"Fire Temple MQ Before Mini Boss Pot 8",
"Fire Temple MQ Outside Boss Pot 1",
"Fire Temple MQ Outside Boss Pot 2",
"Fire Temple MQ Lava Room North Pot",
"Fire Temple MQ Lava Room High Pot",
"Fire Temple MQ Lava Room South Pot",
"Fire Temple MQ Lava Torch Pot 1",
"Fire Temple MQ Lava Torch Pot 2",
"Fire Temple MQ Above Lava Pot 1",
"Fire Temple MQ Above Lava Pot 2",
"Fire Temple MQ Above Lava Pot 3",
"Fire Temple MQ Flame Wall Pot 1",
"Fire Temple MQ Flame Wall Pot 2",
"Fire Temple MQ Past Fire Maze North Pot",
"Fire Temple MQ Past Fire Maze South Pot",
"Fire Temple MQ Fire Maze Northmost Pot",
"Fire Temple MQ Fire Maze North West Pot",
"Fire Temple MQ South Fire Maze W Pot",
"Fire Temple MQ South Fire Maze E Pot",
"Water Temple MQ Lower Torches Pot 1",
"Water Temple MQ Lower Torches Pot 2",
"Water Temple MQ Storage Room A Pot 1",
"Water Temple MQ Storage Room A Pot 2",
"Water Temple MQ Storage Room A Pot 3",
"Water Temple MQ GS Storage Room Pot 1",
"Water Temple MQ GS Storage Room Pot 2",
"Water Temple MQ GS Storage Room Pot 3",
"Water Temple MQ Lizalfos Hall W Pot",
"Water Temple MQ Lizalfos Hall S Pot",
"Water Temple MQ Lizalfos Hall SE Pot",
"Water Temple MQ Lizalfos Cage N Pot",
"Water Temple MQ Lizalfos Cage S Pot",
"Water Temple MQ Stalfos Pit Middle Pot",
"Water Temple MQ Stalfos Pit South Pot",
"Water Temple MQ Stalfos Pit North Pot",
"Water Temple MQ Before Dark Link Pot 1",
"Water Temple MQ Before Dark Link Pot 2",
"Water Temple MQ After Dark Link Pot 1",
"Water Temple MQ After Dark Link Pot 2",
"Water Temple MQ River Pot 1",
"Water Temple MQ River Pot 2",
"Water Temple MQ Boss Key Pot",
"Water Temple MQ Lowest GS Pot 1",
"Water Temple MQ Lowest GS Pot 2",
"Water Temple MQ Lowest GS Pot 3",
"Water Temple MQ Lowest GS Pot 4",
"Gerudo Training Ground MQ Lobby Left Pot 1",
"Gerudo Training Ground MQ Lobby Left Pot 2",
"Gerudo Training Ground MQ Lobby Right Pot 1",
"Gerudo Training Ground MQ Lobby Right Pot 2",
"Water Temple MQ Storage Room B Pot 1",
"Water Temple MQ Storage Room B Pot 2",
"Water Temple MQ Mini Dodongo Pot 1",
"Water Temple MQ Mini Dodongo Pot 2",
"Shadow Temple MQ Whispering Walls Pot 1",
"Shadow Temple MQ Whispering Walls Pot 2",
"Shadow Temple MQ Entrance Redead Pot 1",
"Shadow Temple MQ Entrance Redead Pot 2",
"Shadow Temple MQ Lower Umbrella W Pot",
"Shadow Temple MQ Lower Umbrella E Pot",
"Shadow Temple MQ Upper Umbrella S Pot",
"Shadow Temple MQ Upper Umbrella N Pot",
"Shadow Temple MQ Before Boat Pot 1",
"Shadow Temple MQ Before Boat Pot 2",
"Shadow Temple MQ Before Chasm W Pot",
"Shadow Temple MQ Before Chasm E Pot",
"Shadow Temple MQ After Chasm W Pot",
"Shadow Temple MQ After Chasm E Pot",
"Shadow Temple MQ Spike Baricade Pot",
"Shadow Temple MQ Dead Hand Pot 1",
"Shadow Temple MQ Dead Hand Pot 2",
"Spirit Temple MQ Entrance Pot 1",
"Spirit Temple MQ Entrance Pot 2",
"Spirit Temple MQ Entrance Pot 3",
"Spirit Temple MQ Entrance Pot 4",
"Spirit Temple MQ Child Slugma Pot",
"Spirit Temple MQ Child Gibdo Pot 1",
"Spirit Temple MQ Child Gibdo Pot 2",
"Spirit Temple MQ Child Stalfos Pot 1",
"Spirit Temple MQ Child Stalfos Pot 2",
"Spirit Temple MQ Child Stalfos Pot 3",
"Spirit Temple MQ Child Stalfos Pot 4",
"Spirit Temple MQ Child Like Like Pot",
"Spirit Temple MQ Statue Room 2F CE Pot",
"Spirit Temple MQ Statue Room 3F E Pot",
"Spirit Temple MQ Statue Room 3F W Pot",
"Spirit Temple MQ Statue Room 2F W Pot",
"Spirit Temple MQ Statue Room 2F E Pot",
"Spirit Temple MQ Sun Blocks Pot 1",
"Spirit Temple MQ Sun Blocks Pot 2",
"Spirit Temple MQ Long Climb Pot 1",
"Spirit Temple MQ Long Climb Pot 2",
"Spirit Temple MQ Big Mirror Pot 1",
"Spirit Temple MQ Big Mirror Pot 2",
"Spirit Temple MQ Big Mirror Pot 3",
"Spirit Temple MQ Big Mirror Pot 4",
"Spirit Temple MQ Before Mirror Pot 1",
"Spirit Temple MQ Before Mirror Pot 2",
"Spirit Temple MQ Early Adult Pot 1",
"Spirit Temple MQ Early Adult Pot 2",
"Ice Cavern MQ Entrance Pot",
"Ice Cavern MQ First Crystal Pot 1",
"Ice Cavern MQ First Crystal Pot 2",
"Ice Cavern MQ Early Wolfos Pot 1",
"Ice Cavern MQ Early Wolfos Pot 2",
"Ice Cavern MQ Early Wolfos Pot 3",
"Ice Cavern MQ Early Wolfos Pot 4",
"Ice Cavern MQ Push Block Pot 1",
"Ice Cavern MQ Push Block Pot 2",
"Ice Cavern MQ Compass Pot 1",
"Ice Cavern MQ Compass Pot 2",
"Ganon's Castle MQ Forest Trial Pot 1",
"Ganon's Castle MQ Forest Trial Pot 2",
"Ganon's Castle MQ Water Trial Pot 1",
"Ganon's Castle MQ Water Trial Pot 2",
"Ganon's Castle MQ Shadow Trial Pot 1",
"Ganon's Castle MQ Shadow Trial Pot 2",
"Ganon's Castle MQ Fire Trial Pot 1",
"Ganon's Castle MQ Fire Trial Pot 2",
"Ganon's Castle MQ Light Trial Pot 1",
"Ganon's Castle MQ Light Trial Pot 2",
"Ganon's Castle MQ Spirit Trial Pot 1",
"Ganon's Castle MQ Spirit Trial Pot 2",
"GV Freestanding PoH Crate",
"GV Near Cow Crate",
"GV Near Bridge Crate 1",
"GV Near Bridge Crate 2",
"GV Near Bridge Crate 3",
"GV Near Bridge Crate 4",
"GF Above Jail Crate",
"GF Outside Center Crate 1",
"GF Outside Center Crate 2",
"GF Outside Center Crate 3",
"GF Outside Center Crate 4",
"GF Outside Left Crate 1",
"GF Outside Left Crate 2",
"GF Archery Range Crate 1",
"GF Archery Range Crate 2",
"GF Archery Range Crate 3",
"GF Archery Range Crate 4",
"GF Archery Range Crate 5",
"GF Archery Range Crate 6",
"GF Archery Range Crate 7",
"GF Near Archery Start Crate 1",
"GF Near Archery Start Crate 2",
"GF Archery Left End Crate 1",
"GF Archery Left End Crate 2",
"GF Archery Left End Child Crate",
"GF Archery Right End Crate 1",
"GF Archery Right End Crate 2",
"GF Kitchen Crate 1",
"GF Kitchen Crate 2",
"GF Kitchen Crate 3",
"GF Kitchen Crate 4",
"GF Kitchen Crate 5",
"GF Break Room Crate 1",
"GF Break Room Crate 2",
"GF Break Room Crate 3",
"GF Break Room Crate 4",
"GF North F1 Carpenter Crate",
"GF North F3 Carpenter Crate",
"GF South F2 Carpenter Crate 1",
"GF South F2 Carpenter Crate 2",
"Wasteland Before Quicksand Crate",
"Wasteland After Quicksand Crate 1",
"Wasteland After Quicksand Crate 2",
"Wasteland After Quicksand Crate 3",
"Wasteland Near Colossus Crate",
"Market Near Bazaar Crate 1",
"Market Near Bazaar Crate 2",
"Market Shooting Gallery Crate 1",
"Market Shooting Gallery Crate 2",
"Market Lost Dog House Crate",
"Market Guard House Crate 1",
"Market Guard House Crate 2",
"Market Guard House Crate 3",
"Market Guard House Crate 4",
"Market Guard House Crate 5",
"Kak Near Open Grotto Adult Crate 1",
"Kak Near Open Grotto Adult Crate 2",
"Kak Near Open Grotto Adult Crate 3",
"Kak Near Open Grotto Adult Crate 4",
"Kak Near Potion Shop Adult Crate",
"Kak Near Shooting Gallery Adult Crate",
"Kak Near Boarding House Adult Crate 1",
"Kak Near Boarding House Adult Crate 2",
"Kak Near Impas House Adult Crate 1",
"Kak Near Impas House Adult Crate 2",
"Kak Near Bazaar Adult Crate 1",
"Kak Near Bazaar Adult Crate 2`",
"Kak Behind GS House Adult Crate",
"Kak Near Graveyard Child Crate",
"Kak Near Windmill Child Crate",
"Kak Near Fence Child Crate",
"Kak Near Boarding House Child Crate",
"Kak Near Bazaar Child Crate",
"Graveyard Freestanding PoH Crate",
"GC Maze Crate",
"DMC Crate",
"LLR Near Tree Crate",
"LH Lab Crate",
"Deku Tree MQ Lobby Crate",
"Deku Tree MQ Slingshot Room Crate 1",
"Deku Tree MQ Slingshot Room Crate 2",
"Dodongos Cavern MQ Poe Room Crate 1",
"Dodongos Cavern MQ Poe Room Crate 2",
"Dodongos Cavern MQ Poe Room Crate 3",
"Dodongos Cavern MQ Poe Room Crate 4",
"Dodongos Cavern MQ Poe Room Crate 5",
"Dodongos Cavern MQ Poe Room Crate 6",
"Dodongos Cavern MQ Poe Room Crate 7",
"Dodongos Cavern MQ Poe Room Crate 8",
"Dodongos Cavern MQ Staircase Lower Crate 1",
"Dodongos Cavern MQ Staircase Lower Crate 2",
"Dodongos Cavern MQ Staircase Upper Crate 1",
"Dodongos Cavern MQ Staircase Upper Crate 2",
"Dodongos Cavern MQ Staircase Upper Crate 3",
"Dodongos Cavern MQ Staircase Upper Crate 4",
"Dodongos Cavern MQ Two Flames Crate 1",
"Dodongos Cavern MQ Two Flames Crate 2",
"Dodongos Cavern MQ Larvae Room Crate 1",
"Dodongos Cavern MQ Larvae Room Crate 2",
"Dodongos Cavern MQ Larvae Room Crate 3",
"Dodongos Cavern MQ Larvae Room Crate 4",
"Dodongos Cavern MQ Larvae Room Crate 5",
"Dodongos Cavern MQ Larvae Room Crate 6",
"Fire Temple MQ Outside Boss Crate 1",
"Fire Temple MQ Outside Boss Crate 2",
"Fire Temple MQ Outside Boss Crate 3",
"Fire Temple MQ Outside Boss Crate 4",
"Fire Temple MQ Outside Boss Crate 5",
"Fire Temple MQ Outside Boss Crate 6",
"Fire Temple MQ Shortcut Crate 1",
"Fire Temple MQ Shortcut Crate 2",
"Fire Temple MQ Shortcut Crate 3",
"Fire Temple MQ Shortcut Crate 4",
"Fire Temple MQ Shortcut Crate 5",
"Fire Temple MQ Shortcut Crate 6",
"Fire Temple MQ Lizalfos Maze Lower Crate 1",
"Fire Temple MQ Lizalfos Maze Lower Crate 2",
"Fire Temple MQ Lizalfos Maze Lower Crate 3",
"Fire Temple MQ Lizalfos Maze Upper Crate 1",
"Fire Temple MQ Lizalfos Maze Upper Crate 2",
"Fire Temple MQ Lizalfos Maze Upper Crate 3",
"Fire Temple MQ Lava Torch Crate 1",
"Fire Temple MQ Lava Torch Crate 2",
"Fire Temple MQ Lava Torch Crate 3",
"Fire Temple MQ Lava Torch Crate 4",
"Fire Temple MQ Lava Torch Crate 5",
"Water Temple MQ Central Pillar Upper Crate 1",
"Water Temple MQ Central Pillar Upper Crate 2",
"Water Temple MQ Central Pillar Lower Crate 1",
"Water Temple MQ Central Pillar Lower Crate 2",
"Water Temple MQ Central Pillar Lower Crate 3",
"Water Temple MQ Central Pillar Lower Crate 4",
"Water Temple MQ Central Pillar Lower Crate 5",
"Water Temple MQ Central Pillar Lower Crate 6",
"Water Temple MQ Central Pillar Lower Crate 7",
"Water Temple MQ Central Pillar Lower Crate 8",
"Water Temple MQ Central Pillar Lower Crate 9",
"Water Temple MQ Central Pillar Lower Crate 10",
"Water Temple MQ Central Pillar Lower Crate 11",
"Water Temple MQ Central Pillar Lower Crate 12",
"Water Temple MQ Central Pillar Lower Crate 13",
"Water Temple MQ Central Pillar Lower Crate 14",
"Water Temple MQ Lizalfos Hallway Crate 1",
"Water Temple MQ Lizalfos Hallway Crate 2",
"Water Temple MQ Lizalfos Hallway Crate 3",
"Water Temple MQ Lizalfos Hallway Room Crate 1",
"Water Temple MQ Lizalfos Hallway Room Crate 2",
"Water Temple MQ Lizalfos Hallway Room Crate 3",
"Water Temple MQ Lizalfos Hallway Room Crate 4",
"Water Temple MQ Lizalfos Hallway Room Crate 5",
"Water Temple MQ Lizalfos Hallway Gate Crate 1",
"Water Temple MQ Lizalfos Hallway Gate Crate 2",
"Water Temple MQ Storage Room A Crate 1",
"Water Temple MQ Storage Room A Crate 2",
"Water Temple MQ Storage Room A Crate 3",
"Water Temple MQ Storage Room A Crate 4",
"Water Temple MQ Storage Room A Crate 5",
"Water Temple MQ Storage Room A Crate 6",
"Water Temple MQ Storage Room A Crate 7",
"Water Temple MQ GS Storage Room Lower Crate 1",
"Water Temple MQ GS Storage Room Lower Crate 2",
"Water Temple MQ GS Storage Room Lower Crate 3",
"Water Temple MQ GS Storage Room Lower Crate 4",
"Water Temple MQ GS Storage Room Lower Crate 5",
"Water Temple MQ GS Storage Room Lower Crate 6",
"Water Temple MQ GS Storage Room Upper Crate 1",
"Water Temple MQ GS Storage Room Upper Crate 2",
"Water Temple MQ Dragon Room Torches Crate 1",
"Water Temple MQ Dragon Room Torches Crate 2",
"Water Temple MQ Dragon Room Submerged Crate 1",
"Water Temple MQ Dragon Room Submerged Crate 2",
"Water Temple MQ Dragon Room Submerged Crate 3",
"Water Temple MQ Dragon Room Submerged Crate 4",
"Water Temple MQ Dragon Room Door Crate 1",
"Water Temple MQ Dragon Room Door Crate 2",
"Water Temple MQ BK Room Upper Crate",
"Water Temple MQ BK Room Lower Crate 1",
"Water Temple MQ BK Room Lower Crate 2",
"Water Temple MQ BK Room Lower Crate 3",
"Water Temple MQ BK Room Lower Crate 4",
"Water Temple MQ Whirlpool Front Crate 1",
"Water Temple MQ Whirlpool Front Crate 2",
"Water Temple MQ Whirlpool Submerged Crate 1",
"Water Temple MQ Whirlpool Submerged Crate 2",
"Water Temple MQ Whirlpool Submerged Crate 3",
"Water Temple MQ Whirlpool Submerged Crate 4",
"Water Temple MQ Whirlpool Submerged Crate 5",
"Water Temple MQ Whirlpool Submerged Crate 6",
"Water Temple MQ Whirlpool Behind Gate Crate 1",
"Water Temple MQ Whirlpool Behind Gate Crate 2",
"Water Temple MQ Whirlpool Behind Gate Crate 3",
"Water Temple MQ Whirlpool Behind Gate Crate 4",
"Water Temple MQ Dodongo Room Upper Crate",
"Water Temple MQ Dodongo Room Hall Crate",
"Water Temple MQ Dodongo Room Lower Crate 1",
"Water Temple MQ Dodongo Room Lower Crate 2",
"Water Temple MQ Dodongo Room Lower Crate 3",
"Water Temple MQ Storage Room B Crate 1",
"Water Temple MQ Storage Room B Crate 2",
"Water Temple MQ Storage Room B Crate 3",
"Water Temple MQ Storage Room B Crate 4",
"Water Temple MQ Storage Room B Crate 5",
"Water Temple MQ Triple Torch Room Submerged Crate 1",
"Water Temple MQ Triple Torch Room Submerged Crate 2",
"Water Temple MQ Triple Torch Room Submerged Crate 3",
"Water Temple MQ Triple Torch Room Submerged Crate 4",
"Water Temple MQ Triple Torch Room Submerged Crate 5",
"Water Temple MQ Triple Torch Room Submerged Crate 6",
"Water Temple MQ Triple Torch Room Gate Crate 1",
"Water Temple MQ Triple Torch Room Gate Crate 2",
"Water Temple MQ Triple Torch Room Gate Crate 3",
"Spirit Temple MQ Statue Crate 1",
"Spirit Temple MQ Statue Crate 2",
"Spirit Temple MQ Big Mirror Crate 1",
"Spirit Temple MQ Big Mirror Crate 2",
"Spirit Temple MQ Big Mirror Crate 3",
"Spirit Temple MQ Big Mirror Crate 4",
"Gerudo Training Ground MQ Maze Crate",
"Jabu Jabus Belly Platform Room Small Crate 1",
"Jabu Jabus Belly Platform Room Small Crate 2",
"Fire Temple After Hammer Small Crate 1",
"Fire Temple After Hammer Small Crate 2",
"Spirit Temple Before Child Climb Small Crate 1",
"Spirit Temple Before Child Climb Small Crate 2",
"Jabu Jabus Belly MQ Triple Hallway Small Crate 1",
"Jabu Jabus Belly MQ Triple Hallway Small Crate 2",
"Jabu Jabus Belly MQ Jigglies Small Crate 1",
"Jabu Jabus Belly MQ Jigglies Small Crate 2",
"Forest Temple MQ Frozen Eye Switch Small Crate 1",
"Forest Temple MQ Frozen Eye Switch Small Crate 2",
"Forest Temple MQ Frozen Eye Switch Small Crate 3",
"Fire Temple MQ Lizalfos Maze Upper Small Crate 1",
"Fire Temple MQ Lizalfos Maze Upper Small Crate 2",
"Fire Temple MQ Lava Torch Small Crate 1",
"Fire Temple MQ Lava Torch Small Crate 2",
"Fire Temple MQ Lava Torch Small Crate 3",
"Fire Temple MQ Lava Torch Small Crate 4",
"Fire Temple MQ Lava Torch Small Crate 5",
"Water Temple MQ Dragon Room Torches Small Crate 1",
"Water Temple MQ Dragon Room Torches Small Crate 2",
"Water Temple MQ Dragon Room Torches Small Crate 3",
"Water Temple MQ Storage Room A Small Crate 1",
"Water Temple MQ Storage Room A Small Crate 2",
"Water Temple MQ Storage Room A Small Crate 3",
"Water Temple MQ Storage Room A Small Crate 4",
"Water Temple MQ GS Storage Room Lower Small Crate",
"Water Temple MQ GS Storage Room Upper Small Crate",
"Shadow Temple MQ Truth Spinner Small Crate 1",
"Shadow Temple MQ Truth Spinner Small Crate 2",
"Shadow Temple MQ Truth Spinner Small Crate 3",
"Shadow Temple MQ Truth Spinner Small Crate 4",
"Spirit Temple MQ Statue Small Crate",
"Spirit Temple MQ Beamos Small Crate",
"",
"",
"",
"KF Deku Tree Left Gossip Stone",
"KF Deku Tree Right Gossip Stone",
"KF Gossip Stone",
"KF Storms Gossip Stone",
"LW Gossip Stone",
"LW Near Shortcuts Grotto Gossip Stone",
"SFM Maze Lower Gossip Stone",
"SFM Maze Upper Gossip Stone",
"SFM Saria Gossip Stone",
"HF Cow Grotto Gossip Stone",
"HF Near Market Gossip Stone",
"HF Open Grotto Gossip Stone",
"HF Southeast Gossip Stone",
"Market ToT Left Center Gossip Stone",
"Market ToT Left Gossip Stone",
"Market ToT Right Center Gossip Stone",
"Market ToT Right Gossip Stone",
"HC Malon Gossip Stone",
"HC Rock Wall Gossip Stone",
"HC Storms Grotto Gossip Stone",
"Kak Open Grotto Gossip Stone",
"Graveyard Gossip Stone",
"DMT Gossip Stone",
"DMT Storms Grotto Gossip Stone",
"GC Maze Gossip Stone",
"GC Medigoron Gossip Stone",
"DMC Gossip Stone",
"DMC Upper Grotto Gossip Stone",
"ZR Near Domain Gossip Stone",
"ZR Near Grottos Gossip Stone",
"ZR Open Grotto Gossip Stone",
"ZD Gossip Stone",
"ZF Jabu Gossip Stone",
"ZF Fairy Gossip Stone",
"LH Lab Gossip Stone",
"LH Southeast Gossip Stone",
"LH Southwest Gossip Stone",
"GV Gossip Stone",
"Colossus Gossip Stone",
"Dodongos Cavern Gossip Stone",
"KF Storms Grotto Beehive Left",
"KF Storms Grotto Beehive Right",
"LW Tunnel Grotto Beehive Left",
"LW Tunnel Grotto Beehive Right",
"LW Deku Scrub Grotto Beehive",
"SFM Deku Scrub Grotto Beehive",
"HF Near Market Grotto Beehive Left",
"HF Near Market Grotto Beehive Right",
"HF Open Grotto Beehive Left",
"HF Open Grotto Beehive Right",
"HF Southeast Grotto Beehive Left",
"HF Southeast Grotto Beehive Right",
"HF Deku Scrub Grotto Beehive",
"LLR Deku Scrub Grotto Beehive",
"Kak Open Grotto Beehive Left",
"Kak Open Grotto Beehive Right",
"DMT Cow Grotto Beehive",
"DMT Storms Grotto Beehive Left",
"DMT Storms Grotto Beehive Right",
"GC Grotto Beehive",
"DMC Upper Grotto Beehive Left",
"DMC Upper Grotto Beehive Right",
"DMC Hammer Grotto Beehive",
"ZR Open Grotto Beehive Left",
"ZR Open Grotto Beehive Right",
"ZR Storms Grotto Beehive",
"ZD In Front of King Zora Beehive Left",
"ZD In Front of King Zora Beehive Right",
"ZD Behind King Zora Beehive",
"LH Deku Scrub Grotto Beehive",
"GV Deku Scrub Grotto Beehive",
"Colossus Deku Scrub Grotto Beehive",
"Ganon's Castle Ganondorf Hint",
"Ganon's Castle Sheik Hint",
"Ganon's Castle Sheik Hint",
"Completed Triforce",
"Graveyard Diary Hint",
"Market Greg Hint",
"Magic Hint Via Saria's Song",
"Market ToT Child Altar Hint",
"Market ToT Adult Altar Hint",
"LH Fishing Pole Hint",
"Market Ocarina of Time Hint",
"Market Mask Shop Hint",
"DMC Upper Grotto Fish",
"DMT Storms Grotto Fish",
"HF Southeast Grotto Fish",
"HF Near Market Grotto Fish",
"HF Open Grotto Fish",
"Kak Open Grotto Fish",
"KF Storms Grotto Fish",
"LW Near Shortcuts Grotto Fish",
"ZR Open Grotto Fish",
"ZD Fish 1",
"ZD Fish 2",
"ZD Fish 3",
"ZD Fish 4",
"ZD Fish 5",
"KF Boulder Maze First Rupee",
"KF Boulder Maze Second Rupee",
"KF Bridge Rupee",
"KF Behind Mido's House Rupee",
"KF Saria's Roof West Heart",
"KF Saria's Roof East Heart",
"KF Saria's Roof North Heart",
"KF South Grass West Rupee",
"KF North Grass West Rupee",
"KF North Grass East Rupee",
"KF South Grass East Rupee",
"KF Saria's House Top Left Heart",
"KF Saria's House Top Right Heart",
"KF Saria's House Bottom Left Heart",
"KF Saria's House Bottom Right Heart",
"KF Bean Platform Rupee 1",
"KF Bean Platform Rupee 2",
"KF Bean Platform Rupee 3",
"KF Bean Platform Rupee 4",
"KF Bean Platform Rupee 5",
"KF Bean Platform Rupee 6",
"KF Bean Platform Red Rupee",
"LW Boulder Rupee",
"LW Underwater Shortcut Rupee 1",
"LW Underwater Shortcut Rupee 2",
"LW Underwater Shortcut Rupee 3",
"LW Underwater Shortcut Rupee 4",
"LW Underwater Shortcut Rupee 5",
"LW Underwater Shortcut Rupee 6",
"LW Underwater Shortcut Rupee 7",
"LW Underwater Shortcut Rupee 8",
"LH Underwater Front Rupee",
"LH Underwater Middle Rupee",
"LH Underwater Back Rupee",
"LH Lab Front Rupee",
"LH Lab Left Rupee",
"LH Lab Right Rupee",
"Graveyard Dampe's Grave Rupee 1",
"Graveyard Dampe's Grave Rupee 2",
"Graveyard Dampe's Grave Rupee 3",
"Graveyard Dampe's Grave Rupee 4",
"Graveyard Dampe's Grave Rupee 5",
"Graveyard Dampe's Grave Rupee 6",
"Graveyard Dampe's Grave Rupee 7",
"Graveyard Dampe's Grave Rupee 8",
"GV Octorok Grotto Front Left Blue Rupee",
"GV Octorok Grotto Front Right Blue Rupee",
"GV Octorok Grotto Back Blue Rupee",
"GV Octorok Grotto Front Left Green Rupee",
"GV Octorok Grotto Front Right Green Rupee",
"GV Octorok Grotto Back Left Green Rupee",
"GV Octorok Grotto Back Right Green Rupee",
"GV Octorok Grotto Red Rupee",
"DMT Blue Rupee Under Boulder",
"DMT Red Rupee Under Boulder",
"DMT Cow Grotto Left Heart",
"DMT Cow Grotto Middle Left Heart",
"DMT Cow Grotto Middle Right Heart",
"DMT Cow Grotto Right Heart",
"DMT Cow Grotto Rupee 1",
"DMT Cow Grotto Rupee 2",
"DMT Cow Grotto Rupee 3",
"DMT Cow Grotto Rupee 4",
"DMT Cow Grotto Rupee 5",
"DMT Cow Grotto Rupee 6",
"DMT Cow Grotto Red Rupee",
"DMC Near Warp Platform Red Rupee",
"DMC Middle Platform Red Rupee",
"DMC Middle Platform Blue Rupee 1",
"DMC Middle Platform Blue Rupee 2",
"DMC Middle Platform Blue Rupee 3",
"DMC Middle Platform Blue Rupee 4",
"DMC Middle Platform Blue Rupee 5",
"DMC Middle Platform Blue Rupee 6",
"DMC Distant Platform Red Rupee",
"DMC Distant Platform Rupee 1",
"DMC Distant Platform Rupee 2",
"DMC Distant Platform Rupee 3",
"DMC Distant Platform Rupee 4",
"DMC Distant Platform Rupee 5",
"DMC Distant Platform Rupee 6",
"ZR Beneath Domain Red Left Rupee",
"ZR Beneath Domain Red Middle Left Rupee",
"ZR Beneath Domain Red Middle Right Rupee",
"ZR Beneath Domain Red Right Rupee",
"ZF Bottom North Inner Rupee",
"ZF Bottom Northeast Inner Rupee",
"ZF Bottom Southeast Inner Rupee",
"ZF Bottom South Inner Rupee",
"ZF Bottom Southwest Inner Rupee",
"ZF Bottom Northwest Inner Rupee",
"ZF Bottom North Middle Rupee",
"ZF Bottom Northeast Middle Rupee",
"ZF Bottom Southeast Middle Rupee",
"ZF Bottom South Middle Rupee",
"ZF Bottom Southwest Middle Rupee",
"ZF Bottom Northwest Middle Rupee",
"ZF Bottom North Outer Rupee",
"ZF Bottom Northeast Outer Rupee",
"ZF Bottom Southeast Outer Rupee",
"ZF Bottom South Outer Rupee",
"ZF Bottom Southwest Outer Rupee",
"ZF Bottom Northwest Outer Rupee",
"Deku Tree Lobby Lower Heart",
"Deku Tree Lobby Upper Heart",
"Deku Tree Final Room Left Front Heart",
"Deku Tree Final Room Left Back Heart",
"Deku Tree Final Room Right Heart",
"Dodongos Cavern Lower Lizalfos Room Lavafall Heart",
"Dodongos Cavern Blade Room Heart",
"Dodongos Cavern Upper Lizalfos Room Left Heart",
"Dodongos Cavern Upper Lizalfos Room Right Heart",
"Forest Temple West Courtyard Right Heart",
"Forest Temple West Courtyard Left Heart",
"Forest Temple Well East Heart",
"Forest Temple Well West Heart",
"Fire Temple Fire Pillar Room Left Heart",
"Fire Temple Fire Pillar Room Right Heart",
"Fire Temple Fire Pillar Room Back Heart",
"Fire Temple East Central Room Left Heart",
"Fire Temple East Central Room Right Heart",
"Fire Temple East Central Room Middle Heart",
"Fire Temple Fire Wall Chase East Pillar Heart",
"Fire Temple Fire Wall Chase West Pillar Heart",
"Fire Temple Fire Wall Chase Exit Platform Heart",
"Water Temple River Heart 1",
"Water Temple River Heart 2",
"Water Temple River Heart 3",
"Water Temple River Heart 4",
"Shadow Temple Invisible Blades Left Heart",
"Shadow Temple Invisible Blades Right Heart",
"Shadow Temple Scarecrow Near Ship North Heart",
"Shadow Temple Scarecrow Near Ship South Heart",
"Shadow Temple After Ship Upper Left Heart",
"Shadow Temple After Ship Upper Right Heart",
"Shadow Temple After Ship Lower Heart",
"Spirit Temple Adult Climb Left Heart",
"Spirit Temple Adult Climb Right Heart",
"Bottom of the Well Basement Platform Left Rupee",
"Bottom of the Well Basement Platform Back Left Rupee",
"Bottom of the Well Basement Platform Middle Rupee",
"Bottom of the Well Basement Platform Back Right Rupee",
"Bottom of the Well Basement Platform Right Rupee",
"Bottom of the Well Coffin Room Front Left Heart",
"Bottom of the Well Coffin Room Middle Right Heart",
"Ice Cavern Lobby Rupee",
"Ice Cavern Map Room Left Heart",
"Ice Cavern Map Room Middle Heart",
"Ice Cavern Map Room Right Heart",
"Ice Cavern Sliding Block Room Rupee 1",
"Ice Cavern Sliding Block Room Rupee 2",
"Ice Cavern Sliding Block Room Rupee 3",
"Gerudo Training Ground Beamos South Heart",
"Gerudo Training Ground Beamos East Heart",
"Ganon's Castle Shadow Trial Heart 1",
"Ganon's Castle Shadow Trial Heart 2",
"Ganon's Castle Shadow Trial Heart 3",
"Ganon's Castle Fire Trial Heart",
"Ganon's Castle Spirit Trial Heart",
"Deku Tree MQ Compass Room Heart",
"Deku Tree MQ Deku Baba Heart",
"Deku Tree MQ Lobby Heart",
"Deku Tree MQ Slingshot Room Heart",
"Deku Tree MQ Final Room Left Front Heart",
"Deku Tree MQ Final Room Left Back Heart",
"Deku Tree MQ Final Room Right Heart",
"Dodongos Cavern MQ Lizalfos Room Lavafall Heart",
"Dodongos Cavern MQ Torch Room Invisible Heart",
"Jabu Jabus Belly MQ Lift Room Underwater Rupee 1",
"Jabu Jabus Belly MQ Lift Room Underwater Rupee 2",
"Jabu Jabus Belly MQ Lift Room Underwater Rupee 3",
"Jabu Jabus Belly MQ Lift Room Heart 1",
"Jabu Jabus Belly MQ Lift Room Heart 2",
"Forest Temple MQ West Courtyard Right Heart",
"Forest Temple MQ West Courtyard Middle Heart",
"Forest Temple MQ West Courtyard Left Heart",
"Forest Temple MQ Well Middle Heart",
"Forest Temple MQ Well West Heart",
"Forest Temple MQ Well East Heart",
"Fire Temple MQ Fire Pillar Room Left Heart",
"Fire Temple MQ Fire Pillar Room Right Heart",
"Fire Temple MQ Fire Pillar Room Lower Heart",
"Shadow Temple MQ Invisible Blades Left Heart",
"Shadow Temple MQ Invisible Blades Right Heart",
"Shadow Temple MQ Scarecrow Near Ship North Heart",
"Shadow Temple MQ Scarecrow Near Ship South Heart",
"Shadow Temple MQ After Ship Upper Left Heart",
"Shadow Temple MQ After Ship Upper Right Heart",
"Shadow Temple MQ After Ship Lower Heart",
"Spirit Temple MQ Child Early Left Heart",
"Spirit Temple MQ Child Early Right Heart",
"Bottom of the Well MQ Coffin Room Front Right Invisible Heart",
"Bottom of the Well MQ Bomb Alcove Left Heart",
"Bottom of the Well MQ Bomb Alcove Right Heart",
"Bottom of the Well MQ Coffin Room Middle Left Invisible Heart",
"Bottom of the Well MQ Basement Hallway Front Heart",
"Bottom of the Well MQ Basement Hallway Left Heart",
"Bottom of the Well MQ Basement Hallway Right Heart",
"Ganon's Castle MQ Water Trial Heart",
"Ganon's Castle MQ Light Trial Right Heart",
"Ganon's Castle MQ Light Trial Left Heart",
"SFM Fairy Grotto Fairy 1",
"SFM Fairy Grotto Fairy 2",
"SFM Fairy Grotto Fairy 3",
"SFM Fairy Grotto Fairy 4",
"SFM Fairy Grotto Fairy 5",
"SFM Fairy Grotto Fairy 6",
"SFM Fairy Grotto Fairy 7",
"SFM Fairy Grotto Fairy 8",
"ZR Fairy Grotto Fairy 1",
"ZR Fairy Grotto Fairy 2",
"ZR Fairy Grotto Fairy 3",
"ZR Fairy Grotto Fairy 4",
"ZR Fairy Grotto Fairy 5",
"ZR Fairy Grotto Fairy 6",
"ZR Fairy Grotto Fairy 7",
"ZR Fairy Grotto Fairy 8",
"HF Fairy Grotto Fairy 1",
"HF Fairy Grotto Fairy 2",
"HF Fairy Grotto Fairy 3",
"HF Fairy Grotto Fairy 4",
"HF Fairy Grotto Fairy 5",
"HF Fairy Grotto Fairy 6",
"HF Fairy Grotto Fairy 7",
"HF Fairy Grotto Fairy 8",
"ZD Fairy Grotto Fairy 1",
"ZD Fairy Grotto Fairy 2",
"ZD Fairy Grotto Fairy 3",
"ZD Fairy Grotto Fairy 4",
"ZD Fairy Grotto Fairy 5",
"ZD Fairy Grotto Fairy 6",
"ZD Fairy Grotto Fairy 7",
"ZD Fairy Grotto Fairy 8",
"GF Fairy Grotto Fairy 1",
"GF Fairy Grotto Fairy 2",
"GF Fairy Grotto Fairy 3",
"GF Fairy Grotto Fairy 4",
"GF Fairy Grotto Fairy 5",
"GF Fairy Grotto Fairy 6",
"GF Fairy Grotto Fairy 7",
"GF Fairy Grotto Fairy 8",
"Graveyard Shield Grave Fairy 1",
"Graveyard Shield Grave Fairy 2",
"Graveyard Shield Grave Fairy 3",
"Graveyard Shield Grave Fairy 4",
"Graveyard Shield Grave Fairy 5",
"Graveyard Shield Grave Fairy 6",
"Graveyard Shield Grave Fairy 7",
"Graveyard Shield Grave Fairy 8",
"Ganon's Castle Scrubs Fairy 1",
"Ganon's Castle Scrubs Fairy 2",
"Ganon's Castle Scrubs Fairy 3",
"Ganon's Castle Scrubs Fairy 4",
"Ganon's Castle Scrubs Fairy 5",
"Ganon's Castle Scrubs Fairy 6",
"Ganon's Castle Scrubs Fairy 7",
"Ganon's Castle Scrubs Fairy 8",
"Ganon's Castle MQ Scrubs Fairy 1",
"Ganon's Castle MQ Scrubs Fairy 2",
"Ganon's Castle MQ Scrubs Fairy 3",
"Ganon's Castle MQ Scrubs Fairy 4",
"Ganon's Castle MQ Scrubs Fairy 5",
"Ganon's Castle MQ Scrubs Fairy 6",
"Ganon's Castle MQ Scrubs Fairy 7",
"Ganon's Castle MQ Scrubs Fairy 8",
"Colossus Oasis Fairy 1",
"Colossus Oasis Fairy 2",
"Colossus Oasis Fairy 3",
"Colossus Oasis Fairy 4",
"Colossus Oasis Fairy 5",
"Colossus Oasis Fairy 6",
"Colossus Oasis Fairy 7",
"Colossus Oasis Fairy 8",
"ZR Bean Sprout Fairy 1",
"ZR Bean Sprout Fairy 2",
"ZR Bean Sprout Fairy 3",
"KF Bean Sprout Fairy 1",
"KF Bean Sprout Fairy 2",
"KF Bean Sprout Fairy 3",
"LW Bean Sprout Near Bridge Fairy 1",
"LW Bean Sprout Near Bridge Fairy 2",
"LW Bean Sprout Near Bridge Fairy 3",
"LW Bean Sprout Near Theatre Fairy 1",
"LW Bean Sprout Near Theatre Fairy 2",
"LW Bean Sprout Near Theatre Fairy 3",
"LH Bean Sprout Fairy 1",
"LH Bean Sprout Fairy 2",
"LH Bean Sprout Fairy 3",
"GV Bean Sprout Fairy 1",
"GV Bean Sprout Fairy 2",
"GV Bean Sprout Fairy 3",
"Colossus Bean Sprout Fairy 1",
"Colossus Bean Sprout Fairy 2",
"Colossus Bean Sprout Fairy 3",
"Graveyard Bean Sprout Fairy 1",
"Graveyard Bean Sprout Fairy 2",
"Graveyard Bean Sprout Fairy 3",
"DMC Bean Sprout Fairy 1",
"DMC Bean Sprout Fairy 2",
"DMC Bean Sprout Fairy 3",
"DMT Bean Sprout Fairy 1",
"DMT Bean Sprout Fairy 2",
"DMT Bean Sprout Fairy 3",
"Market ToT Left Gossip Stone Fairy",
"Market ToT Left Gossip Stone Big Fairy",
"Market ToT Left Center Gossip Stone Fairy",
"Market ToT Left Center Gossip Stone Big Fairy",
"Market ToT Right Center Gossip Stone Fairy",
"Market ToT Right Center Gossip Stone Big Fairy",
"Market ToT Right Gossip Stone Fairy",
"Market ToT Right Gossip Stone Big Fairy",
"DMC Gossip Stone Fairy",
"DMC Gossip Stone Big Fairy",
"DMT Gossip Stone Fairy",
"DMT Gossip Stone Big Fairy",
"Colossus Gossip Stone Fairy",
"Colossus Gossip Stone Big Fairy",
"Dodongos Cavern Gossip Stone Fairy",
"Dodongos Cavern Gossip Stone Big Fairy",
"Dodongos Cavern MQ Gossip Stone Fairy",
"Dodongos Cavern MQ Gossip Stone Big Fairy",
"GV Gossip Stone Fairy",
"GV Gossip Stone Big Fairy",
"GC Maze Gossip Stone Fairy",
"GC Maze Gossip Stone Big Fairy",
"GC Medigoron Gossip Stone Fairy",
"GC Medigoron Gossip Stone Big Fairy",
"Graveyard Gossip Stone Fairy",
"Graveyard Gossip Stone Big Fairy",
"HC Malon Gossip Stone Fairy",
"HC Malon Gossip Stone Big Fairy",
"HC Rock Wall Gossip Stone Fairy",
"HC Rock Wall Gossip Stone Big Fairy",
"HC Storms Grotto Gossip Stone Fairy",
"HC Storms Grotto Gossip Stone Big Fairy",
"KF Deku Tree Left Gossip Stone Fairy",
"KF Deku Tree Left Gossip Stone Big Fairy",
"KF Deku Tree Right Gossip Stone Fairy",
"KF Deku Tree Right Gossip Stone Big Fairy",
"KF Gossip Stone Fairy",
"KF Gossip Stone Big Fairy",
"KF Storms Gossip Stone Fairy",
"KF Storms Gossip Stone Big Fairy",
"LH Lab Gossip Stone Fairy",
"LH Lab Gossip Stone Big Fairy",
"LH Southeast Gossip Stone Fairy",
"LH Southeast Gossip Stone Big Fairy",
"LH Southwest Gossip Stone Fairy",
"LH Southwest Gossip Stone Big Fairy",
"LW Gossip Stone Fairy",
"LW Gossip Stone Big Fairy",
"SFM Maze Lower Gossip Stone Fairy",
"SFM Maze Lower Gossip Stone Big Fairy",
"SFM Maze Upper Gossip Stone Fairy",
"SFM Maze Upper Gossip Stone Big Fairy",
"SFM Saria Gossip Stone Fairy",
"SFM Saria Gossip Stone Big Fairy",
"ZD Gossip Stone Fairy",
"ZD Gossip Stone Big Fairy",
"ZF Fairy Gossip Stone Fairy",
"ZF Fairy Gossip Stone Big Fairy",
"ZF Jabu Gossip Stone Fairy",
"ZF Jabu Gossip Stone Big Fairy",
"ZR Near Grottos Gossip Stone Fairy",
"ZR Near Grottos Gossip Stone Big Fairy",
"ZR Near Domain Gossip Stone Fairy",
"ZR Near Domain Gossip Stone Big Fairy",
"HF Cow Grotto Gossip Stone Fairy",
"HF Cow Grotto Gossip Stone Big Fairy",
"HF Near Market Gossip Stone Fairy",
"HF Near Market Gossip Stone Big Fairy",
"HF Southeast Gossip Stone Fairy",
"HF Southeast Gossip Stone Big Fairy",
"HF Open Grotto Gossip Stone Fairy",
"HF Open Grotto Gossip Stone Big Fairy",
"Kak Open Grotto Gossip Stone Fairy",
"Kak Open Grotto Gossip Stone Big Fairy",
"ZR Open Grotto Gossip Stone Fairy",
"ZR Open Grotto Gossip Stone Big Fairy",
"LW Tunnel Grotto Gossip Stone Fairy",
"LW Tunnel Grotto Gossip Stone Big Fairy",
"DMT Storms Grotto Gossip Stone Fairy",
"DMT Storms Grotto Gossip Stone Big Fairy",
"DMC Upper Grotto Gossip Stone Fairy",
"DMC Upper Grotto Gossip Stone Big Fairy",
"LH Island Sun's Song Fairy",
"HF Pond Song of Storms Fairy",
"HF Deku Scrub Grotto Storms Fairy",
"DMT Flag Sun's Song Fairy",
"DMT Cow Grotto Song of Storms Fairy",
"LW Shortcuts Song of Storms Fairy",
"GF Kitchen Sun's Song Fairy",
"LW Scrub Grotto Sun's Song Fairy",
"Graveyard Royal Family's Tomb Sun's Song Fairy",
"Spirit Temple After Boulder Room Sun's Song Fairy",
"Spirit Temple Four Armos Room Sun's Song Fairy",
"Shadow Temple Beamos Song of Storms Fairy",
"Shadow Temple Pit Room Song of Storms Fairy",
"Shadow Temple Wind Hint Sun's Song Fairy",
"Bottom of the Well Basement Sun's Song Fairy",
"Ice Cavern Entrance Song of Storms Fairy",
"Gerudo Training Ground Entrance Song of Storms Fairy",
"Ganon's Castle Spirit Trial Beamos Sun's Song Fairy",
"Fire Temple MQ Lower Loop Stalfos Room Sun's Song Fairy",
"Fire Temple MQ Lower Loop Behind Iron Knuckle Sun's Song Fairy",
"Water Temple MQ Before Dark Link Pilar Sun's Song Fairy",
"Water Temple MQ Before Dark Link Left Song of Storms Fairy",
"Water Temple MQ Before Dark Link Right Sun's Song Fairy",
"Spirit Temple MQ Dinalfos Room Sun's Song Fairy",
"Shadow Temple MQ Beamos Song of Storms Fairy",
"Shadow Temple MQ Pit Room Song of Storms Fairy",
"Shadow Temple MQ Wind Hint Sun's Song Fairy",
"Bottom of the Well MQ East Cell Sun's Song Fairy",
"Bottom of the Well MQ Basement Sun's Song Fairy",
"KF Child Grass 1",
"KF Child Grass 2",
"KF Child Grass 3",
"KF Child Grass 4",
"KF Child Grass 5",
"KF Child Grass 6",
"KF Child Grass 7",
"KF Child Grass 8",
"KF Child Grass 9",
"KF Child Grass 10",
"KF Child Grass 11",
"KF Child Grass 12",
"KF Child Grass Maze 1",
"KF Child Grass Maze 2",
"KF Child Grass Maze 3",
"KF Adult Grass 1",
"KF Adult Grass 2",
"KF Adult Grass 3",
"KF Adult Grass 4",
"KF Adult Grass 5",
"KF Adult Grass 6",
"KF Adult Grass 7",
"KF Adult Grass 8",
"KF Adult Grass 9",
"KF Adult Grass 10",
"KF Adult Grass 11",
"KF Adult Grass 12",
"KF Adult Grass 13",
"KF Adult Grass 14",
"KF Adult Grass 15",
"KF Adult Grass 16",
"KF Adult Grass 17",
"KF Adult Grass 18",
"KF Adult Grass 19",
"KF Adult Grass 20",
"LW Near Shortcuts Grass 1",
"LW Near Shortcuts Grass 2",
"LW Near Shortcuts Grass 3",
"LW After Mido Grass 1",
"LW After Mido Grass 2",
"LW After Mido Grass 3",
"LW Near SFM Grass 1",
"LW Near SFM Grass 2",
"LW Near SFM Grass 3",
"Market Market Grass 1",
"Market Market Grass 2",
"Market Market Grass 3",
"Market Market Grass 4",
"Market Market Grass 5",
"Market Market Grass 6",
"Market Market Grass 7",
"Market Market Grass 8",
"HC Near Storms Grotto Grass 1",
"HC Near Storms Grotto Grass 2",
"Kak Near Graveyard Grass 1",
"Kak Near Graveyard Grass 2",
"Kak Near Graveyard Grass 3",
"Kak Tree Grass 1",
"Kak Tree Grass 2",
"Kak Tree Grass 3",
"Kak Tree Grass 4",
"Kak Tree Grass 5",
"Graveyard Graveyard Grass 1",
"Graveyard Graveyard Grass 2",
"Graveyard Graveyard Grass 3",
"Graveyard Graveyard Grass 4",
"Graveyard Graveyard Grass 5",
"Graveyard Graveyard Grass 6",
"Graveyard Graveyard Grass 7",
"Graveyard Graveyard Grass 8",
"Graveyard Graveyard Grass 9",
"Graveyard Graveyard Grass 10",
"Graveyard Graveyard Grass 11",
"Graveyard Graveyard Grass 12",
"LH LH Grass 1",
"LH LH Grass 2",
"LH LH Grass 3",
"LH LH Grass 4",
"LH LH Grass 5",
"LH LH Grass 6",
"LH LH Grass 7",
"LH LH Grass 8",
"LH LH Grass 9",
"LH LH Grass 10",
"LH LH Grass 11",
"LH LH Grass 12",
"LH LH Grass 13",
"LH LH Grass 14",
"LH LH Grass 15",
"LH LH Grass 16",
"LH LH Grass 17",
"LH LH Grass 18",
"LH LH Grass 19",
"LH LH Grass 20",
"LH LH Grass 21",
"LH LH Grass 22",
"LH LH Grass 23",
"LH LH Grass 24",
"LH LH Grass 25",
"LH LH Grass 26",
"LH LH Grass 27",
"LH LH Grass 28",
"LH LH Grass 29",
"LH LH Grass 30",
"LH LH Grass 31",
"LH LH Grass 32",
"LH LH Grass 33",
"LH LH Grass 34",
"LH LH Grass 35",
"LH LH Grass 36",
"LH LH Child Grass 1",
"LH LH Child Grass 2",
"LH LH Child Grass 3",
"LH LH Child Grass 4",
"LH LH Warp Pad Grass 1",
"LH LH Warp Pad Grass 2",
"HF Near KF Grass 1",
"HF Near KF Grass 2",
"HF Near KF Grass 3",
"HF Near KF Grass 4",
"HF Near KF Grass 5",
"HF Near KF Grass 6",
"HF Near KF Grass 7",
"HF Near KF Grass 8",
"HF Near KF Grass 9",
"HF Near KF Grass 10",
"HF Near KF Grass 11",
"HF Near KF Grass 12",
"HF Near Market Grass 1",
"HF Near Market Grass 2",
"HF Near Market Grass 3",
"HF Near Market Grass 4",
"HF Near Market Grass 5",
"HF Near Market Grass 6",
"HF Near Market Grass 7",
"HF Near Market Grass 8",
"HF Near Market Grass 9",
"HF Near Market Grass 10",
"HF Near Market Grass 11",
"HF Near Market Grass 12",
"HF South Grass 1",
"HF South Grass 2",
"HF South Grass 3",
"HF South Grass 4",
"HF South Grass 5",
"HF South Grass 6",
"HF South Grass 7",
"HF South Grass 8",
"HF South Grass 9",
"HF South Grass 10",
"HF South Grass 11",
"HF South Grass 12",
"HF Central Grass 1",
"HF Central Grass 2",
"HF Central Grass 3",
"HF Central Grass 4",
"HF Central Grass 5",
"HF Central Grass 6",
"HF Central Grass 7",
"HF Central Grass 8",
"HF Central Grass 9",
"HF Central Grass 10",
"HF Central Grass 11",
"HF Central Grass 12",
"ZR Near Tree Grass 1",
"ZR Near Tree Grass 2",
"ZR Near Tree Grass 3",
"ZR Near Tree Grass 4",
"ZR Near Tree Grass 5",
"ZR Near Tree Grass 6",
"ZR Near Tree Grass 7",
"ZR Near Tree Grass 8",
"ZR Near Tree Grass 9",
"ZR Near Tree Grass 10",
"ZR Near Tree Grass 11",
"ZR Near Tree Grass 12",
"ZR Near Freestanding PoH Grass",
"KF Storms Grotto Grass 1",
"KF Storms Grotto Grass 2",
"KF Storms Grotto Grass 3",
"KF Storms Grotto Grass 4",
"LW Near Shortcuts Grotto Grass 1",
"LW Near Shortcuts Grotto Grass 2",
"LW Near Shortcuts Grotto Grass 3",
"LW Near Shortcuts Grotto Grass 4",
"HF Near Market Grotto Grass 1",
"HF Near Market Grotto Grass 2",
"HF Near Market Grotto Grass 3",
"HF Near Market Grotto Grass 4",
"HF Open Grotto Grass 1",
"HF Open Grotto Grass 2",
"HF Open Grotto Grass 3",
"HF Open Grotto Grass 4",
"HF Southeast Grotto Grass 1",
"HF Southeast Grotto Grass 2",
"HF Southeast Grotto Grass 3",
"HF Southeast Grotto Grass 4",
"HF Cow Grotto Grass 1",
"HF Cow Grotto Grass 2",
"Kak Open Grotto Grass 1",
"Kak Open Grotto Grass 2",
"Kak Open Grotto Grass 3",
"Kak Open Grotto Grass 4",
"DMT Storms Grotto Grass 1",
"DMT Storms Grotto Grass 2",
"DMT Storms Grotto Grass 3",
"DMT Storms Grotto Grass 4",
"DMT Cow Grotto Grass 1",
"DMT Cow Grotto Grass 2",
"DMC Upper Grotto Grass 1",
"DMC Upper Grotto Grass 2",
"DMC Upper Grotto Grass 3",
"DMC Upper Grotto Grass 4",
"ZR Open Grotto Grass 1",
"ZR Open Grotto Grass 2",
"ZR Open Grotto Grass 3",
"ZR Open Grotto Grass 4",
"Deku Tree Lobby Grass 1",
"Deku Tree Lobby Grass 2",
"Deku Tree Lobby Grass 3",
"Deku Tree Lobby Grass 4",
"Deku Tree Lobby Grass 5",
"Deku Tree Slingshot Grass 1",
"Deku Tree Slingshot Grass 2",
"Deku Tree Slingshot Grass 3",
"Deku Tree Slingshot Grass 4",
"Deku Tree Compass Grass 1",
"Deku Tree Compass Grass 2",
"Deku Tree Basement Grass 1",
"Deku Tree Basement Grass 2",
"Deku Tree Eye Switch Grass 1",
"Deku Tree Eye Switch Grass 2",
"Deku Tree Eye Switch Grass 3",
"Deku Tree Eye Switch Grass 4",
"Deku Tree Spike Roller Grass 1",
"Deku Tree Spike Roller Grass 2",
"Deku Tree Torches Grass 1",
"Deku Tree Torches Grass 2",
"Deku Tree Larvae Grass 1",
"Deku Tree Larvae Grass 2",
"Deku Tree Before Boss Grass 1",
"Deku Tree Before Boss Grass 2",
"Deku Tree Before Boss Grass 3",
"Dodongos Cavern First Bridge Grass",
"Dodongos Cavern Blade Room Grass",
"Dodongos Cavern Single Eye Grass",
"Dodongos Cavern Before Boss Grass",
"Bottom of the Well Basement Behind Rocks Grass 1",
"Bottom of the Well Basement Behind Rocks Grass 2",
"Bottom of the Well Basement Behind Rocks Grass 3",
"Bottom of the Well Basement Behind Rocks Grass 4",
"Bottom of the Well Basement Behind Rocks Grass 5",
"Bottom of the Well Basement Behind Rocks Grass 6",
"Bottom of the Well Basement Behind Rocks Grass 7",
"Bottom of the Well Basement Behind Rocks Grass 8",
"Bottom of the Well Basement Behind Rocks Grass 9",
"Bottom of the Well Basement Grass 1",
"Bottom of the Well Basement Grass 2",
"Bottom of the Well Basement Grass 3",
"Deku Tree MQ Lobby Grass 1",
"Deku Tree MQ Lobby Grass 2",
"Deku Tree MQ Lobby Grass 3",
"Deku Tree MQ Lobby Grass 4",
"Deku Tree MQ Lobby Grass 5",
"Deku Tree MQ Lobby Grass 6",
"Deku Tree MQ Lobby Grass 7",
"Deku Tree MQ Slingshot Grass 1",
"Deku Tree MQ Slingshot Grass 2",
"Deku Tree MQ Slingshot Grass 3",
"Deku Tree MQ Slingshot Grass 4",
"Deku Tree MQ Before Compass Grass 1",
"Deku Tree MQ Before Compass Grass 2",
"Deku Tree MQ Before Compass Grass 3",
"Deku Tree MQ Before Compass Grass 4",
"Deku Tree MQ Before Compass Grass 5",
"Deku Tree MQ Before Compass Grass 6",
"Deku Tree MQ Before Compass Grass 7",
"Deku Tree MQ Compass Grass 1",
"Deku Tree MQ Compass Grass 2",
"Deku Tree MQ Compass Grass 3",
"Deku Tree MQ Compass Grass 4",
"Deku Tree MQ Basement Lower Grass 1",
"Deku Tree MQ Basement Lower Grass 2",
"Deku Tree MQ Basement Lower Grass 3",
"Deku Tree MQ Basement Lower Grass 4",
"Deku Tree MQ Basement Upper Grass 1",
"Deku Tree MQ Basement Upper Grass 2",
"Deku Tree MQ Basement Upper Grass 3",
"Deku Tree MQ Spike Roller Front Grass 1",
"Deku Tree MQ Spike Roller Front Grass 2",
"Deku Tree MQ Spike Roller Front Grass 3",
"Deku Tree MQ Spike Roller Back Grass 1",
"Deku Tree MQ Spike Roller Back Grass 2",
"Deku Tree MQ Torches Grass 1",
"Deku Tree MQ Torches Grass 2",
"Deku Tree MQ Torches Grass 3",
"Deku Tree MQ Torches Grass 4",
"Deku Tree MQ Larvae Grass 1",
"Deku Tree MQ Larvae Grass 2",
"Deku Tree MQ Graves Grass 1",
"Deku Tree MQ Graves Grass 2",
"Deku Tree MQ Graves Grass 3",
"Deku Tree MQ Graves Grass 4",
"Deku Tree MQ Graves Grass 5",
"Deku Tree MQ Back Grass 1",
"Deku Tree MQ Back Grass 2",
"Deku Tree MQ Back Grass 3",
"Deku Tree MQ Before Boss Grass 1",
"Deku Tree MQ Before Boss Grass 2",
"Deku Tree MQ Before Boss Grass 3",
"Dodongos Cavern MQ Compass Grass 1",
"Dodongos Cavern MQ Compass Grass 2",
"Dodongos Cavern MQ Compass Grass 3",
"Dodongos Cavern MQ Compass Grass 4",
"Dodongos Cavern MQ Armos Grass",
"Dodongos Cavern MQ Back Poe Grass",
"Dodongos Cavern MQ Scrub Grass 1",
"Dodongos Cavern MQ Scrub Grass 2",
"Jabu Jabus Belly MQ First Grass 1",
"Jabu Jabus Belly MQ First Grass 2",
"Jabu Jabus Belly MQ Pit Grass 1",
"Jabu Jabus Belly MQ Pit Grass 2",
"Jabu Jabus Belly MQ Basement Grass 1",
"Jabu Jabus Belly MQ Basement Grass 2",
"Jabu Jabus Belly MQ Basement Grass 3",
"Jabu Jabus Belly MQ Jigglies Grass",
"Jabu Jabus Belly MQ After Big Octo Grass 1",
"Jabu Jabus Belly MQ After Big Octo Grass 2",
"Jabu Jabus Belly MQ Like Like Grass",
"Jabu Jabus Belly MQ Basement Boomerang Grass",
"Jabu Jabus Belly MQ Before Boss Grass 1",
"Jabu Jabus Belly MQ Before Boss Grass 2",
"Bottom of the Well MQ Dead Hand Grass 1",
"Bottom of the Well MQ Dead Hand Grass 2",
"Bottom of the Well MQ Dead Hand Grass 3",
"Bottom of the Well MQ Dead Hand Grass 4",
"Deku Tree Queen Gohma Grass 1",
"Deku Tree Queen Gohma Grass 2",
"Deku Tree Queen Gohma Grass 3",
"Deku Tree Queen Gohma Grass 4",
"Deku Tree Queen Gohma Grass 5",
"Deku Tree Queen Gohma Grass 6",
"Deku Tree Queen Gohma Grass 7",
"Deku Tree Queen Gohma Grass 8"
]

loc_id_by_name = {name: id for id, name in enumerate(locations)}

entrances = [
    #Entrance name, Location 1 name, Location 2 name, Access rule
]