
overworld_regions = [
    {
        "name": "Root",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Root Exits",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Child Spawns",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Adult Spawns",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Minuet of Forest Warp",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Bolero of Fire Warp",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Serenade of Water Warp",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Requiem of Spirit Warp",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Nocturne of Shadow Warp",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Prelude of Light Warp",
        "scene": "",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kokiri Forest",
        "scene": "Kokiri Forest",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "KF Outside Deku Tree",
        "scene": "Kokiri Forest",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "KF Link's House",
        "scene": "KF Link's House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "KF Mido's House",
        "scene": "KF Mido's House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "KF Saria's House",
        "scene": "KF Saria's House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "KF House of Twins",
        "scene": "KF House of Twins",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "KF Know It All House",
        "scene": "KF Know It All House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "KF Kokiri Shop",
        "scene": "KF Kokiri Shop",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "KF Storms Grotto",
        "scene": "KF Storms Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LW Forest Exit",
        "scene": "Lost Woods",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Lost Woods",
        "scene": "Lost Woods",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LW Beyond Mido",
        "scene": "Lost Woods",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LW Near Shortcuts Grotto",
        "scene": "LW Near Shortcuts Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Deku Theater",
        "scene": "Deku Theater",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LW Scrubs Grotto",
        "scene": "LW Scrubs Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LW Bridge From Forest",
        "scene": "Lost Woods",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LW Bridge",
        "scene": "Lost Woods",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "SFM Entryway",
        "scene": "Sacred Forest Meadow",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Sacred Forest Meadow",
        "scene": "Sacred Forest Meadow",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "SFM Fairy Grotto",
        "scene": "SFM Fairy Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "SFM Wolfos Grotto",
        "scene": "SFM Wolfos Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "SFM Storms Grotto",
        "scene": "SFM Storms Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Hyrule Field",
        "scene": "Hyrule Field",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HF Southeast Grotto",
        "scene": "HF Southeast Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HF Open Grotto",
        "scene": "HF Open Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HF Inside Fence Grotto",
        "scene": "HF Inside Fence Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HF Cow Grotto",
        "scene": "HF Cow Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HF Cow Grotto Behind Webs",
        "scene": "HF Cow Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HF Near Market Grotto",
        "scene": "HF Near Market Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HF Fairy Grotto",
        "scene": "HF Fairy Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HF Near Kak Grotto",
        "scene": "HF Near Kak Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HF Tektite Grotto",
        "scene": "HF Tektite Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Lake Hylia",
        "scene": "Lake Hylia",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LH Fishing Island",
        "scene": "Lake Hylia",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LH Owl Flight",
        "scene": "Lake Hylia",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LH Lab",
        "scene": "LH Lab",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LH Fishing Hole",
        "scene": "LH Fishing Hole",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LH Grotto",
        "scene": "LH Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Lon Lon Ranch",
        "scene": "Lon Lon Ranch",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LLR Talons House",
        "scene": "LLR Talons House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LLR Stables",
        "scene": "LLR Stables",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LLR Tower",
        "scene": "LLR Tower",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "LLR Grotto",
        "scene": "LLR Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Entrance",
        "scene": "Market Entrance",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market",
        "scene": "Market",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Back Alley",
        "scene": "Market",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Guard House",
        "scene": "Market Guard House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Bazaar",
        "scene": "Market Bazaar",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Mask Shop",
        "scene": "Market Mask Shop",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Shooting Gallery",
        "scene": "Market Shooting Gallery",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Bombchu Bowling",
        "scene": "Market Bombchu Bowling",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Potion Shop",
        "scene": "Market Potion Shop",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Treasure Chest Game",
        "scene": "Market Treasure Chest Game",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Bombchu Shop",
        "scene": "Market Bombchu Shop",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Dog Lady House",
        "scene": "Market Dog Lady House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Market Man in Green House",
        "scene": "Market Man in Green House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "ToT Entrance",
        "scene": "ToT Entrance",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Temple of Time",
        "scene": "Temple of Time",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Beyond Door of Time",
        "scene": "Beyond Door of Time",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Castle Grounds",
        "scene": "Castle Grounds",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Hyrule Castle Grounds",
        "scene": "Castle Grounds",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HC Garden",
        "scene": "Castle Grounds",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HC Great Fairy Fountain",
        "scene": "HC Great Fairy Fountain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HC Storms Grotto",
        "scene": "HC Storms Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "HC Storms Grotto Behind Walls",
        "scene": "HC Storms Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Ganon's Castle Grounds",
        "scene": "Castle Grounds",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "OGC Great Fairy Fountain",
        "scene": "OGC Great Fairy Fountain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Castle Grounds From Ganon's Castle",
        "scene": "Castle Grounds From Ganon's Castle",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Ganon's Castle Ledge",
        "scene": "OGC Ganon's Castle Ledge",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kakariko Village",
        "scene": "Kakariko Village",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Impas Ledge",
        "scene": "Kakariko Village",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Impas Rooftop",
        "scene": "Kakariko Village",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Watchtower",
        "scene": "Kakariko Village",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Rooftop",
        "scene": "Kakariko Village",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Backyard",
        "scene": "Kakariko Village",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Carpenter Boss House",
        "scene": "Kak Carpenter Boss House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak House of Skulltula",
        "scene": "Kak House of Skulltula",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Impas House",
        "scene": "Kak Impas House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Impas House Back",
        "scene": "Kak Impas House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Windmill",
        "scene": "Windmill and Dampes Grave",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Bazaar",
        "scene": "Kak Bazaar",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Shooting Gallery",
        "scene": "Kak Shooting Gallery",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Potion Shop Front",
        "scene": "Kak Potion Shop",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Potion Shop Back",
        "scene": "Kak Potion Shop",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Granny's Potion Shop",
        "scene": "Kak Granny's Potion Shop",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Redead Grotto",
        "scene": "Kak Redead Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Open Grotto",
        "scene": "Kak Open Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Behind Gate",
        "scene": "Kakariko Village",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Kak Well",
        "scene": "Kakariko Village",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "The Graveyard",
        "scene": "The Graveyard",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Graveyard Shield Grave",
        "scene": "Graveyard Shield Grave",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Graveyard Shield Grave Back",
        "scene": "Graveyard Shield Grave",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Graveyard Heart Piece Grave",
        "scene": "Graveyard Heart Piece Grave",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Graveyard Composers Grave",
        "scene": "Graveyard Composers Grave",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Graveyard Composers Grave",
        "scene": "Windmill and Dampes Grave",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Graveyard Dampes House",
        "scene": "Graveyard Dampes House",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Graveyard Warp Pad Region",
        "scene": "The Graveyard",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Death Mountain",
        "scene": "Death Mountain",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Death Mountain Summit",
        "scene": "Death Mountain",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMT Owl Flight",
        "scene": "Death Mountain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMT Cow Grotto",
        "scene": "DMT Cow Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMT Storms Grotto",
        "scene": "DMT Storms Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMT Great Fairy Fountain",
        "scene": "DMT Great Fairy Fountain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Goron City",
        "scene": "Goron City",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GC Medigoron",
        "scene": "Goron City",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GC Woods Warp",
        "scene": "Goron City",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GC Darunias Chamber",
        "scene": "Goron City",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GC Grotto Platform",
        "scene": "Goron City",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GC Shop",
        "scene": "GC Shop",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GC Grotto",
        "scene": "GC Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Upper Nearby",
        "scene": "Death Mountain Crater",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Upper Local",
        "scene": "Death Mountain Crater",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Ladder Region Nearby",
        "scene": "Death Mountain Crater",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Lower Nearby",
        "scene": "Death Mountain Crater",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Lower Local",
        "scene": "Death Mountain Crater",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Central Nearby",
        "scene": "Death Mountain Crater",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Central Local",
        "scene": "Death Mountain Crater",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Great Fairy Fountain",
        "scene": "DMC Great Fairy Fountain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Upper Grotto",
        "scene": "DMC Upper Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Hammer Grotto",
        "scene": "DMC Hammer Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "DMC Distant Platform",
        "scene": "Death Mountain Crater",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "ZR Front",
        "Scene": "Zora River",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Zora River",
        "Scene": "Zora River",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "ZR Behind Waterfall",
        "Scene": "Zora River",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "ZR Fairy Grotto",
        "scene": "ZR Fairy Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "ZR Storms Grotto",
        "scene": "ZR Storms Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Zoras Domain",
        "scene": "Zoras Domain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Zoras Domain Island",
        "scene": "Zoras Domain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "ZD Behind King Zora",
        "scene": "Zoras Domain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "ZD Shop",
        "scene": "ZD Shop",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "ZD Storms Grotto",
        "scene": "ZD Storms Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Zoras Fountain",
        "scene": "Zoras Fountain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "ZF Great Fairy Fountain",
        "scene": "ZF Great Fairy Fountain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Gerudo Valley",
        "scene": "Gerudo Valley",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GV Upper Stream",
        "scene": "Gerudo Valley",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GV Lower Stream",
        "scene": "Gerudo Valley",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GV Grotto Ledge",
        "scene": "Gerudo Valley",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GV Crate Ledge",
        "scene": "Gerudo Valley",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GV Fortress Side",
        "scene": "Gerudo Valley",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GV Carpenter Tent",
        "scene": "GV Carpenter Tent",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GV Octorock Grotto",
        "scene": "GV Octorock Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GV Storms Grotto",
        "scene": "GV Storms Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Gerudo Fortress",
        "scene": "Gerudo Fortress",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GF Outside Gate",
        "scene": "Gerudo Fortress",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "GF Storms Grotto",
        "scene": "GF Storms Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Wasteland Near Fortress",
        "scene": "Haunted Wasteland",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Haunted Wasteland",
        "scene": "Haunted Wasteland",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Desert Colossus",
        "scene": "Desert Colossus",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Desert Colossus Oasis",
        "scene": "Desert Colossus",
        "time_passes": True,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Desert Colossus From Spirit Entryway",
        "scene": "Desert Colossus",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Colossus Great Fairy Fountain",
        "scene": "Colossus Great Fairy Fountain",
        "time_passes": False,
        "locations": [],
        "exits": [],
    },
    {
        "name": "Colossus Grotto",
        "scene": "Colossus Grotto",
        "time_passes": False,
        "locations": [],
        "exits": [],
    }
]